import { Crop, TranslationMap, Disease, ExpertTip } from './types';

export const EXPERT_TIPS: ExpertTip[] = [
  {
    id: 'soil_health_1',
    category: 'soil',
    icon: 'Database',
    title: {
      en: 'Boost Soil Organic Matter',
      hi: 'मिट्टी के कार्बनिक पदार्थों को बढ़ाएं',
      bn: 'মাটির জৈব পদার্থ বৃদ্ধি করুন',
      mr: 'मातीतील सेंद्रिय पदार्थ वाढवा',
      te: 'నేల సేంద్రియ పదార్థాన్ని పెంచండి',
      ta: 'மண் கரிமப் பொருட்களை அதிகரிக்கவும்',
      gu: 'જમીનમાં સેન્દ્રિય પદાર્થો વધારો',
      kn: 'ಮಣ್ಣಿನ ಸಾವಯವ ಪದಾರ್ಥವನ್ನು ಹೆಚ್ಚಿಸಿ'
    },
    content: {
      en: 'Incorporate compost or green manure to improve soil structure and water retention.',
      hi: 'मिट्टी की संरचना और जल धारण क्षमता में सुधार के लिए खाद या हरी खाद का प्रयोग करें।',
      bn: 'মাটির গঠন এবং জল ধারণ ক্ষমতা উন্নত করতে কম্পোস্ট বা সবুজ সার ব্যবহার করুন।',
      mr: 'मातीची रचना आणि पाणी धरून ठेवण्याची क्षमता सुधारण्यासाठी कंपोस्ट किंवा हिरवळीचे खत वापरा।',
      te: 'నేల నిర్మాణం మరియు నీటి నిలుపుదల సామర్థ్యాన్ని మెరుగుపరచడానికి కంపోస్ట్ లేదా పచ్చిరొట్ట ఎరువును వాడండి।',
      ta: 'மண் அமைப்பு மற்றும் நீர் தேக்கும் திறனை மேம்படுத்த உரம் அல்லது பசுந்தாள் உரத்தைச் சேர்க்கவும்।',
      gu: 'જમીનનું બંધારણ અને જળ સંગ્રહ ક્ષમતા સુધારવા માટે ખાતર અથવા લીલો પડવાશ ઉમેરો।',
      kn: 'ಮಣ್ಣಿನ ರಚನೆ ಮತ್ತು ನೀರು ಹಿಡಿದಿಟ್ಟುಕೊಳ್ಳುವ ಸಾಮರ್ಥ್ಯವನ್ನು ಸುಧಾರಿಸಲು ಕಾಂಪೋಸ್ಟ್ ಅಥವಾ ಹಸಿರು ಗೊಬ್ಬರವನ್ನು ಸೇರಿಸಿ.'
    }
  },
  {
    id: 'pest_control_1',
    category: 'pest',
    icon: 'Bug',
    title: {
      en: 'Natural Pest Control',
      hi: 'प्राकृतिक कीट नियंत्रण',
      bn: 'প্রাকৃতিক কীট নিয়ন্ত্রণ',
      mr: 'नैसर्गिक कीड नियंत्रण',
      te: 'సహజ తెగుళ్ల నియంత్రణ',
      ta: 'இயற்கை பூச்சி கட்டுப்பாடு',
      gu: 'કુદરતી જંતુ નિયંત્રણ',
      kn: 'ನೈಸರ್ಗಿಕ ಕೀಟ ನಿಯಂತ್ರಣ'
    },
    content: {
      en: 'Use Neem oil spray to control aphids and whiteflies without harming beneficial insects.',
      hi: 'लाभकारी कीटों को नुकसान पहुँचाए बिना एफिड्स और सफेद मक्खियों को नियंत्रित करने के लिए नीम के तेल के स्प्रे का उपयोग करें।',
      bn: 'উপকারী পতঙ্গদের ক্ষতি না করে এফিডস এবং হোয়াইটফ্লাই নিয়ন্ত্রণে নিম তেলের স্প্রে ব্যবহার করুন।',
      mr: 'फायदेशीर कीटकांना इजा न पोहोचवता मावा आणि पांढरी माशी नियंत्रित करण्यासाठी कडुनिंबाच्या तेलाची फवारणी करा।',
      te: 'ప్రయోజనకరమైన కీటకాలకు హాని చేయకుండా అఫిడ్స్ మరియు తెల్లదోమలను నియంత్రించడానికి వేప నూనె పిచಿಕారీని వాడండి।',
      ta: 'நன்மை செய்யும் பூச்சிகளுக்கு தீங்கு விளைவிக்காமல் அசுவினி மற்றும் வெள்ளை ஈக்களைக் கட்டுப்படுத்த வேப்ப எண்ணெய் தெளிப்பைப் பயன்படுத்தவும்।',
      gu: 'ફાયદાકારક જંતુઓને નુકસાન પહોંચાડ્યા વિના એફિડ્સ અને સફેદ માખીઓને નિયંત્રિત કરવા માટે લીમડાના તેલનો છંટકાવ કરો।',
      kn: 'ಉಪಕಾರಿ ಕೀಟಗಳಿಗೆ ಹಾನಿ ಮಾಡದೆ ಅಫಿಡ್‌ಗಳು ಮತ್ತು ಬಿಳಿ ನೊಣಗಳನ್ನು ನಿಯಂತ್ರಿಸಲು ಬೇವಿನ ಎಣ್ಣೆ ಸಿಂಪರಣೆಯನ್ನು ಬಳಸಿ.'
    }
  },
  {
    id: 'seasonal_1',
    category: 'seasonal',
    icon: 'CloudSun',
    title: {
      en: 'Monsoon Preparation',
      hi: 'मानसून की तैयारी',
      bn: 'বর্ষার প্রস্তুতি',
      mr: 'पावसाळ्याची तयारी',
      te: 'వర్షాకాలం తయారీ',
      ta: 'மழைக்காலத் தயாரிப்பு',
      gu: 'ચોમાસાની તૈયારી',
      kn: 'ಮುಂಗಾರು ತಯಾರಿ'
    },
    content: {
      en: 'Ensure proper drainage in fields before heavy rains to prevent waterlogging and root rot.',
      hi: 'जलभराव और जड़ों के सड़ने से बचने के लिए भारी बारिश से पहले खेतों में जल निकासी की उचित व्यवस्था सुनिश्चित करें।',
      bn: 'জলবদ্ধতা এবং শিকড় পচা রোধ করতে ভারী বৃষ্টির আগে জমিতে সঠিক নিষ্কাশন ব্যবস্থা নিশ্চিত করুন।',
      mr: 'पाणी साचणे आणि मुळे कुजणे टाळण्यासाठी मुसळधार पावसापूर्वी शेतात पाण्याचा निचरा होण्याची योग्य व्यवस्था करा।',
      te: 'నీరు నిలవకుండా మరియు వేరు కుళ్లును నివారించడానికి భారీ వర్షాలకు ముందే పొలాల్లో సరైన నీటి పారుదల సౌకర్యాన్ని నిర్ధారించుకోండి।',
      ta: 'நீர் தேங்குதல் மற்றும் வேர் அழுகலைத் தடுக்க கனமழைக்கு முன்னதாக வயல்களில் முறையான வடிகால் வசதியை உறுதி செய்யவும்।',
      gu: 'પાણી ભરાઈ જવાથી અને મૂળના સડાને રોકવા માટે ભારે વરસાદ પહેલા ખેતરોમાં યોગ્ય નિકાલની વ્યવસ્થા સુનિશ્ચિત કરો।',
      kn: 'ನೀರು ನಿಲ್ಲುವುದು ಮತ್ತು ಬೇರು ಕೊಳೆಯುವುದನ್ನು ತಡೆಯಲು ಭಾರಿ ಮಳೆಯ ಮೊದಲು ಹೊಲಗಳಲ್ಲಿ ಸರಿಯಾದ ಒಳಚರಂಡಿ ವ್ಯವಸ್ಥೆಯನ್ನು ಖಚಿತಪಡಿಸಿಕೊಳ್ಳಿ.'
    }
  }
];

export const DISEASES: Disease[] = [
  {
    id: 'cotton_bacterial_blight',
    name: { en: 'Bacterial Blight', hi: 'जीवाणु झुलसा', bn: 'ব্যাকটেরিয়াল ব্লাইট', mr: 'जीवाणूजन्य करपा', te: 'బ్యాక్టీరియా ఎండు తెగులు', ta: 'பாக்டீரியா வாடல் நோய்', gu: 'બેક્ટેરિયલ સુકારો', kn: 'ಹತ್ತಿ ಬ್ಯಾಕ್ಟೀರಿಯಲ್ ಬ್ಲೈಟ್' },
    crop: 'cotton',
    symptoms: { en: 'Angular leaf spots and boll rot.', hi: 'कोणीय पत्ती के धब्बे और डोडों का सड़ना।', bn: 'কৌণিক পাতার দাগ এবং বোল পচা।', mr: 'कोनीय पानांवरील ठिपके आणि बोंड सडणे।', te: 'కోణీయ ఆకు మచ్చలు మరియు కాయ కుళ్లు।', ta: 'கோண இலை புள்ளிகள் மற்றும் காய் அழுகல்।', gu: 'કોણીય પાંદડાના ડાઘ અને જીંડવા સડો।', kn: 'ಕೋನೀಯ ಎಲೆ ಕಲೆಗಳು ಮತ್ತು ಕಾಯಿ ಕೊಳೆತ.' },
    treatment: { en: 'Seed treatment and Copper Oxychloride.', hi: 'बीज उपचार और कॉपर ऑक्सीक्लोराइड।', bn: 'বীজ শোধন এবং কপার অক্সিক্লোরাইড।', mr: 'बीजप्रक्रिया आणि कॉपर ऑक्सीक्लोराइड।', te: 'విత్తన శుద్ధి మరియు కాపర్ ఆక్సిక్లోరైడ్।', ta: 'விதை நேர்த்தி மற்றும் காப்பர் ஆக்ஸிகுளோரைடு।', gu: 'બીજ માવજત અને కోపర్ ఆక్సిక్లోరైడ్।', kn: 'ಬೀಜೋಪಚಾರ ಮತ್ತು ಕಾಪರ್ ಆಕ್ಸಿಕ್లోರೈಡ್.' },
    steps: { en: ['Use resistant varieties', 'Clean cultivation', 'Spray bactericide'], hi: ['प्रतिरोधी किस्मों का प्रयोग करें', 'स्वच्छ खेती', 'जीवाणुनाशक का छिड़काव करें'], bn: ['প্রতিরোধী জাত ব্যবহার করুন', 'পরিচ্ছন্ন চাষাবাদ', 'ব্যাকটেরিয়া নাশক স্প্রে করুন'], mr: ['प्रतिकारक्षम वाण वापरा', 'स्वच्छ शेती', 'जीवाणूनाशकाची फवारणी करा'], te: ['వరదలను నివారించండి', 'పొటాష్ ఎరువును వాడండి', 'బాక్టీరిసైడ్ పిచికారీ చేయండి'], ta: ['வெள்ளத்தைத் தவிர்க்கவும்', 'பொட்டாஷ் உரத்தைப் பயன்படுத்தவும்', 'பாக்டீரியா கொல்லியைத் தெளிக்கவும்'], gu: ['પૂર ટાળો', 'પોટાશ ખાતર લગાવો', 'બેક્ટેરિસાઇડ છાંટો'], kn: ['ಪ್ರವಾಹವನ್ನು ತಪ್ಪಿಸಿ', 'ಪೊಟ್ಯಾಶ್ ಗೊಬ್ಬರವನ್ನು ಬಳಸಿ', 'ಬ್ಯಾಕ್ಟೀರಿಸೈಡ್ ಸಿಂಪಡಿಸಿ'] },
    dosage: { en: '3g per liter water', hi: '3 ग्राम प्रति लीटर पानी', bn: 'প্রতি লিটার জলে ৩ গ্রাম', mr: '३ ग्रॅम प्रति लिटर पाणी', te: 'లీటరు నీటికి 3 గ్రాములు', ta: 'ஒரு லிட்டர் தண்ணீருக்கு 3 கிராம்', gu: 'લિટર દીઠ ૩ ગ્રામ પાણી', kn: 'ಪ್ರತಿ ಲೀಟರ್ ನೀರಿಗೆ 3 ಗ್ರಾಂ' },
    application: { en: 'Foliar spray', hi: 'पत्तियों पर छिड़काव', bn: 'পাতায় স্প্রে', mr: 'फवारणी', te: 'పిచికారీ', ta: 'இலைத் தெளிப்பு', gu: 'છંટકાવ', kn: 'ಎಲೆಗಳ ಮೇಲೆ సింಪಡಣೆ' },
    severity: 'High'
  },
  {
    id: 'rice_blast',
    name: { en: 'Rice Blast', hi: 'धान का झोंका', bn: 'ধানের ব্লাস্ট', mr: 'भातावरील करपा', te: 'వరి అగ్గి తెగులు', ta: 'நெல் குலை நோய்', gu: 'ડાંગરનો બ્લાસ્ટ', kn: 'ಭತ್ತದ ಬ್ಲಾಸ್ಟ್' },
    crop: 'rice',
    symptoms: { en: 'Spindle-shaped spots on leaves.', hi: 'पत्तियों पर धुरी के आकार के धब्बे।', bn: 'পাতায় মাকু আকৃতির দাগ।', mr: 'पानांवर लांबट ठिपके।', te: 'ఆకులపై నూలు కండె ఆకారపు మచ్చలు।', ta: 'இலைகளில் கதிர் வடிவிலான புள்ளிகள்।', gu: 'પાંદડા પર ત્રાક આકારના ડાઘ।', kn: 'ಎಲೆಗಳ ಮೇಲೆ ಕದಿರು ಆಕಾರದ ಕಲೆಗಳು.' },
    treatment: { en: 'Tricyclazole or Carbendazim.', hi: 'ट्राइसाइक्लाज़ोल या कार्बेन्डाजिम।', bn: 'ট্রাইসাইক্লাজোল বা কার্বেন্ডাজিম।', mr: 'ट्रायसायक्लाझोल किंवा कार्बेन्डाझिम।', te: 'ట్రైసైక్లాజోల్ లేదా కార్బెండజిమ్।', ta: 'ட்ரைசைக்ளோசோல் அல்லது கார்பென்டாசிம்।', gu: 'ટ્રાયસાઇક્લાઝોલ અથવા કાર્બેન્ડાઝિમ।', kn: 'ಟ್ರೈಸೈಕ್ಲಾಜೋಲ್ ಅಥವಾ ಕಾರ್ಬೆಂಡಾಜಿಮ್.' },
    steps: { en: ['Avoid excess nitrogen', 'Seed treatment', 'Spray fungicide'], hi: ['अत्यधिक नाइट्रोजन से बचें', 'बीज उपचार', 'कवकनाशी का छिड़काव करें'], bn: ['অতিরিক্ত নাইট্রোজেন এড়িয়ে চলুন', 'বীজ শোধন', 'ছত্রাকনাশক স্প্রে করুন'], mr: ['जास्त नत्र वापरणे टाळा', 'बीजप्रक्रिया', 'बुरशीनाशकाची फवारणी करा'], te: ['అధిక నత్రజనిని నివారించండి', 'విత్తన శుద్ధి', 'శిలీంధ్ర నాశిని పిచಿಕారీ చేయండి'], ta: ['அதிகப்படியான தழைச்சத்தைத் தவிர்க்கவும்', 'விதை நேர்த்தி', 'பூஞ்சைக் கொல்லியைத் தெளிக்கவும்'], gu: ['વધારે નાઇટ્રોજન ટાળો', 'બીજ માવજત', 'ફૂગનાશક છાંટો'], kn: ['ಹೆಚ್ಚಿನ ಸಾರಜನಕವನ್ನು ತಪ್ಪಿಸಿ', 'ಬೀಜೋಪಚಾರ', 'ಶಿಲೀಂಧ್ರನಾಶಕ ಸಿಂಪಡಿಸಿ'] },
    dosage: { en: '0.6g per liter water', hi: '0.6 ग्राम प्रति लीटर पानी', bn: 'প্রতি লিটার জলে ০.৬ গ্রাম', mr: '०.६ ग्रॅम प्रति लिटर पाणी', te: 'లీటరు నీటికి 0.6 గ్రాములు', ta: 'ஒரு லிட்டர் தண்ணீருக்கு 0.6 கிராம்', gu: 'લિટર દીઠ ૦.૬ ગ્રામ પાણી', kn: 'ಪ್ರತಿ ಲೀಟರ್ ನೀರಿಗೆ 0.6 ಗ್ರಾಂ' },
    application: { en: 'Foliar spray', hi: 'पत्तियों पर छिड़काव', bn: 'পাতায় স্প্রে', mr: 'फवारणी', te: 'పిచಿಕారీ', ta: 'இலைத் தெளிப்பு', gu: 'છંટకાવ', kn: 'ಎಲೆಗಳ ಮೇಲೆ ಸಿಂಪಡಣೆ' },
    severity: 'High'
  },
  {
    id: 'wheat_rust',
    name: { en: 'Wheat Rust', hi: 'गेहूं का रतुआ', bn: 'গমের মরিচা', mr: 'गव्हावरील तांबेरा', te: 'గోధుమ తుప్పు తెగులు', ta: 'கோதுமை துரு நோய்', gu: 'ઘઉંનો ગેરુ', kn: 'ಗೋಧಿ ತುಕ್ಕು ರೋಗ' },
    crop: 'wheat',
    symptoms: { en: 'Orange or brown pustules on leaves.', hi: 'पत्तियों पर नारंगी या भूरे रंग के छाले।', bn: 'পাতায় কমলা বা বাদামী রঙের পুস্টুল।', mr: 'पानांवर नारंगी किंवा तपकिरी रंगाचे फोड।', te: 'ఆకులపై నారింజ లేదా గోధుమ రంగు మచ్చలు।', ta: 'இலைகளில் ஆரஞ்சு அல்லது பழுப்பு நிற கொப்புளங்கள்।', gu: 'પાંદડા પર નારંગી અથવા કથ્થઈ રંગના ચાંદા।', kn: 'ಎಲೆಗಳ ಮೇಲೆ ಕಿತ್ತಳೆ ಅಥವಾ ಕಂದು ಬಣ್ಣದ ಗುಳ್ಳೆಗಳು.' },
    treatment: { en: 'Propiconazole or Tebuconazole.', hi: 'प्रोपिकोनाज़ोल या टेबुकोनाज़ोल।', bn: 'প্রোপিকোনাজোল বা টেবুকোনাজোল।', mr: 'प्रोपिकोनाझोल किंवा टेबुकोनाझोल।', te: 'ప్రొపికోనజోల్ లేదా టెబుకొనజోల్।', ta: 'புரோபிகோனசோல் அல்லது டெபுகோனசோல்।', gu: 'પ્રોપિકોનાઝોલ અથવા ટેબુકોનાઝોલ।', kn: 'ಪ್ರೊಪಿಕೊನಾಜೋಲ್ ಅಥವಾ ಟೆಬುಕೊನಾಜೋಲ್.' },
    steps: { en: ['Use resistant varieties', 'Early sowing', 'Spray fungicide'], hi: ['प्रतिरोधी किस्मों का प्रयोग करें', 'जल्दी बुवाई', 'कवकनाशी का छिड़काव करें'], bn: ['প্রতিরোধী জাত ব্যবহার করুন', 'আগাম বপন', 'ছত্রাকনাশক স্প্রে করুন'], mr: ['प्रतिकारक्षम वाण वापरा', 'लवकर पेरणी', 'बुरशीनाशकाची फवारणी करा'], te: ['నిరోధక రకాలను వాడండి', 'ముందస్తు విత్తడం', 'శిలీంధ్ర నాశిని పిచికారీ చేయండి'], ta: ['எதிர்ப்புத் திறன் கொண்ட ரகங்களைப் பயன்படுத்தவும்', 'முன்கூட்டியே விதைத்தல்', 'பூஞ்சைக் கொல்லியைத் தெளிக்கவும்'], gu: ['પ્રતિકારક જાતો વાપરો', 'વહેલી વાવણી', 'ફૂગનાશક છાંટો'], kn: ['ನಿರೋಧಕ ತಳಿಗಳನ್ನು ಬಳಸಿ', 'ಬೇಗ ಬಿತ್ತನೆ ಮಾಡಿ', 'ಶಿಲೀಂಧ್ರನಾಶಕ ಸಿಂಪಡಿಸಿ'] },
    dosage: { en: '1ml per liter water', hi: '1 मिली प्रति लीटर पानी', bn: 'প্রতি লিটার জলে ১ মিলি', mr: '१ मिली प्रति लिटर पाणी', te: 'లీటరు నీటికి 1 మి.లీ', ta: 'ஒரு லிட்டர் தண்ணீருக்கு 1 மி.லி', gu: 'લિટર દીઠ ૧ મિલી પાણી', kn: 'ಪ್ರತಿ ಲೀಟರ್ ನೀರಿಗೆ 1 ಮಿಲಿ' },
    application: { en: 'Foliar spray', hi: 'पत्तियों पर छिड़काव', bn: 'পাতায় স্প্রে', mr: 'फवारणी', te: 'పిచికారీ', ta: 'இலைத் தெளிப்பு', gu: 'છંટકાવ', kn: 'ಎಲೆಗಳ ಮೇಲೆ ಸಿಂಪಡಣೆ' },
    severity: 'High'
  },
  {
    id: 'tomato_early_blight',
    name: { en: 'Early Blight', hi: 'अगेती झुलसा', bn: 'আর্লি ব্লাইট', mr: 'लवकर येणारा करपा', te: 'ముందస్తు ఎండు తెగులు', ta: 'ஆரம்பகால வாடல் நோய்', gu: 'વહેલો સુકારો', kn: 'ಟೊಮೆಟೊ ಅರ್ಲಿ ಬ್ಲೈಟ್' },
    crop: 'tomato',
    symptoms: { en: 'Target-like spots on older leaves.', hi: 'पुरानी पत्तियों पर लक्ष्य जैसे धब्बे।', bn: 'পুরানো পাতায় টার্গেটের মতো দাগ।', mr: 'जुन्या पानांवर गोलाकार ठिपके।', te: 'ముదురు ఆకులపై వలయాకారపు మచ్చలు।', ta: 'முதிர்ந்த இலைகளில் இலக்கு போன்ற புள்ளிகள்।', gu: 'જૂના પાંદડા પર ટાર્ગેટ જેવા ડાઘ।', kn: 'ಹಳೆಯ ಎಲೆಗಳ ಮೇಲೆ ಗುರಿ ಆಕಾರದ ಕಲೆಗಳು.' },
    treatment: { en: 'Mancozeb or Chlorothalonil.', hi: 'मैनकोजेब या क्लोरोथालोनिल।', bn: 'ম্যানকোজেব বা ক্লোরোথ্যালোনিল।', mr: 'मँकोझेब किंवा क्लोरोथॅलोनिल।', te: 'మాంకోజెబ్ లేదా క్లోరోథలోనిల్।', ta: 'மன்கோசெப் அல்லது குளோரோதலோனில்।', gu: 'મેન્કોઝેબ અથવા ક્લોરોથેલોનિલ।', kn: 'ಮ್ಯಾಂಕೋಜೆಬ್ ಅಥವಾ ಕ್ಲೋರೋಥಲೋನಿಲ್.' },
    steps: { en: ['Crop rotation', 'Remove infected leaves', 'Spray fungicide'], hi: ['फसल चक्र', 'संक्रमित पत्तियों को हटा दें', 'कवकनाशी का छिड़काव करें'], bn: ['ফসল আবর্তন', 'আক্রান্ত পাতা সরিয়ে ফেলুন', 'ছত্রাকনাশক স্প্রে করুন'], mr: ['पीक फेरपालट', 'बाधित पाने काढून टाका', 'बुरशीनाशकाची फवारणी करा'], te: ['పంట మార్పిడి', 'వ్యాధి సోకిన ఆకులను తొలగించండి', 'శిలీంధ్ర నాశిని పిచికారీ చేయండి'], ta: ['பயிர் சுழற்சி', 'பாதிக்கப்பட்ட இலைகளை அகற்றவும்', 'பூஞ்சைக் கொல்லியைத் தெளிக்கவும்'], gu: ['પાક ફેરબદલી', 'ચેપગ્રસ્ત પાંદડા દૂર કરો', 'ફૂગનાશક છાંટો'], kn: ['ಬೆಳೆ ಸರದಿ', 'ಸೋಂಕಿತ ಎಲೆಗಳನ್ನು ತೆಗೆದುಹಾಕಿ', 'ಶಿಲೀಂಧ್ರನಾಶಕ ಸಿಂಪಡಿಸಿ'] },
    dosage: { en: '2g per liter water', hi: '2 ग्राम प्रति लीटर पानी', bn: 'প্রতি লিটার জলে ২ গ্রাম', mr: '२ ग्रॅम प्रति लिटर पाणी', te: 'లీటరు నీటికి 2 గ్రాములు', ta: 'ஒரு லிட்டர் தண்ணீருக்கு 2 கிராம்', gu: 'લિટર દીઠ ૨ ગ્રામ પાણી', kn: 'ಪ್ರತಿ ಲೀಟರ್ ನೀರಿಗೆ 2 ಗ್ರಾಂ' },
    application: { en: 'Foliar spray', hi: 'पत्तियों पर छिड़काव', bn: 'পাতায় স্প্রে', mr: 'फवारणी', te: 'పిచಿಕారీ', ta: 'இலைத் தெளிப்பு', gu: 'છંટகાવ', kn: 'ಎಲೆಗಳ ಮೇಲೆ ಸಿಂಪಡಣೆ' },
    severity: 'Medium'
  },
  {
    id: 'maize_downy_mildew',
    name: { en: 'Downy Mildew', hi: 'डाउनी मिल्ड्यू', bn: 'ডাউনি মিলডিউ', mr: 'केवडा रोग', te: 'డౌనీ మిల్డ్యూ', ta: 'அடிச்சாம்பல் நோய்', gu: 'તળછારો', kn: 'ಮೆಕ್ಕೆಜೋಳದ ಡೌನಿ ಮಿಲ್ಡ್ಯೂ' },
    crop: 'maize',
    symptoms: { en: 'Whitish growth on leaf underside.', hi: 'पत्ती के निचले हिस्से पर सफेद वृद्धि।', bn: 'পাতার নিচের দিকে সাদাটে বৃদ্ধি।', mr: 'पानांच्या खालच्या बाजूला पांढरी वाढ।', te: 'ఆకు అడుగు భాగంలో తెల్లటి పెరుగుదల।', ta: 'இலையின் அடிப்பகுதியில் வெண்மையான வளர்ச்சி।', gu: 'પાંદડાની નીચેની બાજુએ સફેદ વૃદ્ધિ।', kn: 'ಎಲೆಯ ಕೆಳಭಾಗದಲ್ಲಿ ಬಿಳಿ ಬಣ್ಣದ ಬೆಳವಣಿಗೆ.' },
    treatment: { en: 'Metalaxyl or Mancozeb.', hi: 'मेटलैक्सिल या मैनकोजेब।', bn: 'মেটালাক্সিল বা ম্যানকোজেব।', mr: 'मेटालॅक्सिल किंवा मँकोझेब।', te: 'మెటాలాక్సిల్ లేదా మాంకోజెబ్।', ta: 'மெட்டாலாக்ஸில் அல்லது மன்கோசெப்।', gu: 'મેટાલૅક્સિલ અથવા મેન્કોઝેબ।', kn: 'ಮೆಟಾಲಾಕ್ಸಿಲ್ ಅಥವಾ ಮ್ಯಾಂಕೋಜೆಬ್.' },
    steps: { en: ['Seed treatment', 'Improve drainage', 'Spray fungicide'], hi: ['बीज उपचार', 'जल निकासी में सुधार', 'कवकनाशी का छिड़काव करें'], bn: ['বীজ শোধন', 'নিষ্কাশন ব্যবস্থার উন্নতি', 'ছত্রাকনাশক স্প্রে করুন'], mr: ['बीजप्रक्रिया', 'पाण्याचा निचरा सुधारा', 'बुरशीनाशकाची फवारणी करा'], te: ['విత్తన శుద్ధి', 'నీటి పారుదల మెరుగుపరచండి', 'శిలీంధ్ర నాశిని పిచికారీ చేయండి'], ta: ['விதை நேர்த்தி', 'வடிகால் வசதியை மேம்படுத்தவும்', 'பூஞ்சைக் கொல்லியைத் தெளிக்கவும்'], gu: ['બીજ માવજત', 'નિકાલમાં સુધારો', 'ફૂગનાશક છાંટો'], kn: ['ಬೀಜೋಪಚಾರ', 'ಒಳಚರಂಡಿ ಸುಧಾರಿಸಿ', 'ಶಿಲೀಂಧ್ರನಾಶಕ ಸಿಂಪಡಿಸಿ'] },
    dosage: { en: '2g per liter water', hi: '2 ग्राम प्रति लीटर पानी', bn: 'প্রতি লিটার জলে ২ গ্রাম', mr: '२ ग्रॅम प्रति लिटर पाणी', te: 'లీటరు నీటికి 2 గ్రాములు', ta: 'ஒரு லிட்டர் தண்ணீருக்கு 2 கிராம்', gu: 'લિટર દીઠ ૨ ગ્રામ પાણી', kn: 'ಪ್ರತಿ ಲೀಟರ್ ನೀರಿಗೆ 2 ಗ್ರಾಂ' },
    application: { en: 'Foliar spray', hi: 'पत्तियों पर छिड़काव', bn: 'পাতায় স্প্রে', mr: 'फवारणी', te: 'పిచಿಕారీ', ta: 'இலைத் தெளிப்பு', gu: 'છંટகાવ', kn: 'ಎಲೆಗಳ ಮೇಲೆ ಸಿಂಪಡಣೆ' },
    severity: 'Medium'
  },
  {
    id: 'rice_brown_spot',
    name: { en: 'Brown Spot', hi: 'भूरा धब्बा', bn: 'বাদামী দাগ', mr: 'तपकिरी ठिपके', te: 'గోధుమ రంగు మచ్చ తెగులు', ta: 'பழுப்பு புள்ளி நோய்', gu: 'બ્રાઉન સ્પોટ', kn: 'ಭತ್ತದ ಕಂದು ಕಲೆ ರೋಗ' },
    crop: 'rice',
    symptoms: { en: 'Small oval brown spots on leaves.', hi: 'पत्तियों पर छोटे अंडाकार भूरे धब्बे।', bn: 'পাতায় ছোট ডিম্বাকৃতি বাদামী দাগ।', mr: 'पानांवर लहान लंबवर्तुळाकार तपकिरी ठिपके।', te: 'ఆకులపై చిన్న అండాకారపు గోధుమ రంగు మచ్చలు।', ta: 'இலைகளில் சிறிய முட்டை வடிவ பழுப்பு நிற புள்ளிகள்।', gu: 'પાંદડા પર નાના અંડાકાર કથ્થઈ ડાઘ।', kn: 'ಎಲೆಗಳ ಮೇಲೆ ಸಣ್ಣ ಅಂಡಾಕಾರದ ಕಂದು ಕಲೆಗಳು.' },
    treatment: { en: 'Mancozeb or Edifenphos.', hi: 'मैनकोजेब या एडिफेनफोस।', bn: 'ম্যানকোজেব বা এডিফেনফস।', mr: 'मँकोझेब किंवा एडिफेनफॉस।', te: 'మాంకోజెబ్ లేదా ఎడిఫెన్‌ఫాస్।', ta: 'மன்கோசெப் அல்லது எடிஃபென்போஸ்।', gu: 'મેન્કોઝેબ અથવા એડિફેનફોસ।', kn: 'ಮ್ಯಾಂಕೋಜೆಬ್ ಅಥವಾ ಎಡಿಫೆನ್ಫೋಸ್.' },
    steps: { en: ['Balanced fertilization', 'Seed treatment', 'Spray fungicide'], hi: ['संतुलित उर्वरक', 'बीज उपचार', 'कवकनाशी का छिड़काव करें'], bn: ['সুষম সার প্রয়োগ', 'বীজ শোধন', 'ছত্রাকনাশক স্প্রে করুন'], mr: ['संतुलित खत वापर', 'बीजप्रक्रिया', 'बुरशीनाशकाची फवारणी करा'], te: ['సమతుల్య ఎరువులు', 'విత్తన శుద్ధి', 'శిలీంధ్ర నాశిని పిచికారీ చేయండి'], ta: ['சீரான உரமிடுதல்', 'விதை நேர்த்தி', 'பூஞ்சைக் கொல்லியைத் தெளிக்கவும்'], gu: ['સંતુલિત ખાતર', 'બીજ માવજત', 'ફૂગનાશક છાંટો'], kn: ['ಸಮತೋಲಿತ ಗೊಬ್ಬರ', 'ಬೀಜೋಪಚಾರ', 'ಶಿಲೀಂಧ್ರನಾಶಕ ಸಿಂಪಡಿಸಿ'] },
    dosage: { en: '2g per liter water', hi: '2 ग्राम प्रति लीटर पानी', bn: 'প্রতি লিটার জলে ২ গ্রাম', mr: '२ ग्रॅम प्रति लिटर पाणी', te: 'లీటరు నీటికి 2 గ్రాములు', ta: 'ஒரு லிட்டர் தண்ணீருக்கு 2 கிராம்', gu: 'લિટર દીઠ ૨ ગ્રામ પાણી', kn: 'ಪ್ರತಿ ಲೀಟರ್ ನೀರಿಗೆ 2 ಗ್ರಾಂ' },
    application: { en: 'Foliar spray', hi: 'पत्तियों पर छिड़काव', bn: 'পাতায় স্প্রে', mr: 'फवारणी', te: 'పిచിക്കారీ', ta: 'இலைத் தெளிப்பு', gu: 'છંટકાવ', kn: 'ಎಲೆಗಳ ಮೇಲೆ ಸಿಂಪಡಣೆ' },
    severity: 'Low'
  }
];

export const CROPS: Crop[] = [
  {
    id: 'wheat',
    name: { 
      en: 'Wheat', hi: 'गेहूं', bn: 'গম', mr: 'गहू', te: 'గోధుమ', ta: 'கோதுமை', gu: 'ઘઉં', kn: 'ಗೋಧಿ' 
    },
    minPh: 6.0,
    maxPh: 7.5,
    minTemp: 10,
    maxTemp: 25,
    waterRequirement: 'Medium',
    sowingMonths: [10, 11, 12],
    description: {
      en: 'Major cereal grain, staple food in many regions.',
      hi: 'प्रमुख अनाज, कई क्षेत्रों में मुख्य भोजन।',
      bn: 'প্রধান শস্য, অনেক অঞ্চলের প্রধান খাদ্য।',
      mr: 'प्रमुख तृणधान्य, अनेक प्रदेशांतील मुख्य अन्न।',
      te: 'ప్రధాన తృణధాన్యం, అనేక ప్రాంతాలలో ప్రధాన ఆహారం।',
      ta: 'முக்கிய தானியம், பல பகுதிகளில் முக்கிய உணவு।',
      gu: 'મુખ્ય અનાજ, ઘણા પ્રદેશોમાં મુખ્ય ખોરાક।',
      kn: 'ಪ್ರಮುಖ ಧಾನ್ಯ, ಅನೇಕ ಪ್ರದೇಶಗಳಲ್ಲಿ ಪ್ರಮುಖ ಆಹಾರ.'
    },
    soilType: { 
      en: 'Well-drained Loam', hi: 'अच्छी जल निकासी वाली दोमट', bn: 'সুনিষ্কাশিত দোআঁশ', mr: 'पाण्याचा निचरा होणारी लोम माती',
      te: 'మంచి నీటి పారుదల గల లోమ్', ta: 'நல்ல வடிகால் வசதியுள்ள வண்டல் மண்', gu: 'સારી નિકાલવાળી ગોરાડુ માટી', kn: 'ಉತ್ತಮ ನೀರು ಹರಿಯುವ ಲೋಮ್'
    },
    yieldPotential: { 
      en: '3.5 - 4.5 tons/hectare', hi: '3.5 - 4.5 टन/हेक्टेयर', bn: '৩.৫ - ৪.৫ টন/হেক্টর', mr: '३.५ - ४.५ टन/हेक्टर',
      te: '3.5 - 4.5 టన్నులు/హెక్టారు', ta: '3.5 - 4.5 டன்/ஹெக்டேர்', gu: '3.5 - 4.5 ટન/હેક્ટર', kn: '3.5 - 4.5 ಟನ್/ಹೆಕ್ಟೇರ್'
    },
    rotationGroup: 'cereal'
  },
  {
    id: 'rice',
    name: { 
      en: 'Rice (Paddy)', hi: 'धान (चावल)', bn: 'ধান (চাল)', mr: 'भात (धान)', te: 'వరి', ta: 'நெல்', gu: 'ડાંગર (ચોખા)', kn: 'ಭತ್ತ (ಅಕ್ಕಿ)' 
    },
    minPh: 5.5,
    maxPh: 7.0,
    minTemp: 20,
    maxTemp: 35,
    waterRequirement: 'High',
    sowingMonths: [6, 7],
    description: {
      en: 'Primary food source for a large part of the world population.',
      hi: 'दुनिया की एक बड़ी आबादी के लिए प्राथमिक भोजन स्रोत।',
      bn: 'বিশ্বের জনসংখ্যার একটি বড় অংশের জন্য প্রাথমিক খাদ্য উৎস।',
      mr: 'जगातील लोकसंख्येच्या मोठ्या भागासाठी प्राथमिक अन्न स्रोत.',
      te: 'ప్రపంచ జనాభాలో ఎక్కువ భాగానికి ప్రాథమిక ఆహార వనరు.',
      ta: 'உலகின் பெரும்பகுதி மக்களின் முதன்மை உணவு ஆதாரம்.',
      gu: 'વિશ્વની વસ્તીના મોટા ભાગ માટે પ્રાથમિક ખોરાક સ્ત્રોત.',
      kn: 'ವಿಶ್ವದ ಜನಸಂಖ್ಯೆಯ ಹೆಚ್ಚಿನ ಭಾಗಕ್ಕೆ ಪ್ರಾಥಮಿಕ ಆಹಾರ ಮೂಲ.'
    },
    soilType: { 
      en: 'Clayey Loam', hi: 'चिकनी दोमट', bn: 'এঁটেল দোআঁশ', mr: 'चिकण लोम माती',
      te: 'బంకమట్టి లోమ్', ta: 'களிமண் வண்டல்', gu: 'ચીકણી ગોરાડુ માટી', kn: 'ಜಿಗುಟು ಲೋಮ್'
    },
    yieldPotential: { 
      en: '4.0 - 6.0 tons/hectare', hi: '4.0 - 6.0 टन/हेक्टेयर', bn: '৪.০ - ৬.০ টন/হেক্টর', mr: '४.० - ६.० टन/हेक्टर',
      te: '4.0 - 6.0 టన్నులు/హెక్టారు', ta: '4.0 - 6.0 டன்/ஹெக்டேர்', gu: '4.0 - 6.0 ટન/હેક્ટર', kn: '4.0 - 6.0 ಟನ್/ಹೆಕ್ಟೇರ್'
    },
    rotationGroup: 'cereal'
  },
  {
    id: 'maize',
    name: { 
      en: 'Maize (Corn)', hi: 'मक्का', bn: 'ভুট্টা', mr: 'मका', te: 'మొక్కజొన్న', ta: 'சோளம்', gu: 'મકાઈ', kn: 'ಮೆಕ್ಕೆಜೋಳ' 
    },
    minPh: 5.8,
    maxPh: 7.0,
    minTemp: 18,
    maxTemp: 32,
    waterRequirement: 'Medium',
    sowingMonths: [6, 7, 10, 11],
    description: {
      en: 'Versatile cereal crop used for food and fodder.',
      hi: 'भोजन और चारे के लिए उपयोग की जाने वाली बहुमुखी अनाज की फसल।',
      bn: 'খাদ্য এবং পশুখাদ্য হিসাবে ব্যবহৃত বহুমুখী শস্য।',
      mr: 'अन्न आणि चाऱ्यासाठी वापरले जाणारे बहुमुखी तृणधान्य पीक.',
      te: 'ఆహారం మరియు పశుగ్రాసం కోసం ఉపయోగించే బహుముఖ తృణధాన్యం.',
      ta: 'உணவு மற்றும் தீவனத்திற்காக பயன்படுத்தப்படும் பல்துறை தானியப் பயிர்.',
      gu: 'ખોરાક અને ઘાસચારા માટે વપરાતો બહુમુખી અનાજ પાક.',
      kn: 'ಆಹಾರ ಮತ್ತು ಮೇವಿಗಾಗಿ ಬಳಸಲಾಗುವ ಬಹುಮುಖ ಧಾನ್ಯದ ಬೆಳೆ.'
    },
    soilType: { 
      en: 'Deep Loam', hi: 'गहरी दोमट', bn: 'গভীর দোআঁশ', mr: 'खोल लोम माती',
      te: 'లోతైన లోమ్', ta: 'ஆழமான வண்டல் மண்', gu: 'ઊંડી ગોરાડુ માટી', kn: 'ಆಳವಾದ ಲೋಮ್'
    },
    yieldPotential: { 
      en: '5.0 - 8.0 tons/hectare', hi: '5.0 - 8.0 टन/हेक्टेयर', bn: '৫.০ - ৮.০ টন/হেক্টর', mr: '५.० - ८.० टन/हेक्टर',
      te: '5.0 - 8.0 టన్నులు/హెక్టారు', ta: '5.0 - 8.0 டன்/ஹெக்டேர்', gu: '5.0 - 8.0 ટન/હેક્ટર', kn: '5.0 - 8.0 ಟನ್/ಹೆಕ್ಟೇರ್'
    },
    rotationGroup: 'cereal'
  },
  {
    id: 'mustard',
    name: { 
      en: 'Mustard', hi: 'सरसों', bn: 'সরিষা', mr: 'मोहरी', te: 'ఆవాలు', ta: 'கடுகு', gu: 'રાયડો', kn: 'ಸಾಸಿವೆ' 
    },
    minPh: 6.0,
    maxPh: 7.5,
    minTemp: 10,
    maxTemp: 25,
    waterRequirement: 'Low',
    sowingMonths: [10, 11],
    description: {
      en: 'Important oilseed crop grown in winter.',
      hi: 'सर्दियों में उगाई जाने वाली महत्वपूर्ण तिलहन फसल।',
      bn: 'শীতকালে জন্মায় এমন গুরুত্বপূর্ণ তৈলবীজ ফসল।',
      mr: 'हिवाळ्यात घेतले जाणारे महत्त्वाचे तेलबिया पीक.',
      te: 'శీతాకాలంలో పండించే ముఖ్యమైన నూనెగింజల పంట.',
      ta: 'குளிர்காலத்தில் வளர்க்கப்படும் முக்கியமான எண்ணெய் வித்து பயிர்.',
      gu: 'શિયાળામાં ઉગાડવામાં આવતો મહત્વનો તેલીબિયાં પાક.',
      kn: 'ಚಳಿಗಾಲದಲ್ಲಿ ಬೆಳೆಯುವ ಪ್ರಮುಖ ಎಣ್ಣೆಕಾಳು ಬೆಳೆ.'
    },
    soilType: { 
      en: 'Sandy Loam', hi: 'बलुई दोमट', bn: 'বেলে দোআঁশ', mr: 'रेताड लोम माती',
      te: 'ఇసుక లోమ్', ta: 'மணல் கலந்த வண்டல் மண்', gu: 'રેતાળ ગોરાડુ માટી', kn: 'ಮರಳು ಮಿಶ್ರಿತ ಲೋಮ್'
    },
    yieldPotential: { 
      en: '1.5 - 2.5 tons/hectare', hi: '1.5 - 2.5 टन/हेक्टेयर', bn: '১.৫ - ২.৫ টন/হেক্টর', mr: '१.५ - २.५ टन/हेक्टर',
      te: '1.5 - 2.5 టన్నులు/హెక్టారు', ta: '1.5 - 2.5 டன்/ஹெக்டேர்', gu: '1.5 - 2.5 ટન/હેક્ટર', kn: '1.5 - 2.5 ಟನ್/ಹೆಕ್ಟೇರ್'
    },
    rotationGroup: 'oilseed'
  },
  {
    id: 'tomato',
    name: { 
      en: 'Tomato', hi: 'टमाटर', bn: 'টমেটো', mr: 'टोमॅটো', te: 'టమోటా', ta: 'தக்காளி', gu: 'ટમેટા', kn: 'ಟೊಮೆಟೊ' 
    },
    minPh: 6.0,
    maxPh: 7.0,
    minTemp: 15,
    maxTemp: 30,
    waterRequirement: 'Medium',
    sowingMonths: [6, 7, 10, 11, 1, 2],
    description: {
      en: 'Popular vegetable crop, rich in vitamins.',
      hi: 'लोकप्रिय सब्जी की फसल, विटामिन से भरपूर।',
      bn: 'জনপ্রিয় সবজি ফসল, ভিটামিন সমৃদ্ধ।',
      mr: 'लोकप्रिय भाजीपाला पीक, जीवनसत्त्वांनी समृद्ध.',
      te: 'ప్రసిద్ధ కూరగాయల పంట, విటమిన్లు పుష్కలంగా ఉంటాయి.',
      ta: 'பிரபலமான காயறி பயிர், வைட்டமின்கள் நிறைந்தது.',
      gu: 'લોકપ્રિય શાકભાજી પાક, વિટામિન્સથી ભરપૂર.',
      kn: 'ಜನಪ್ರಿಯ ತರಕಾರಿ ಬೆಳೆ, ಜೀವಸತ್ವಗಳಿಂದ ಸಮೃದ್ಧವಾಗಿದೆ.'
    },
    soilType: { 
      en: 'Well-drained Loam', hi: 'अच्छी जल निकासी वाली दोमट', bn: 'সুনিষ্কাশিত দোআঁশ', mr: 'पाण्याचा निचरा होणारी लोम माती',
      te: 'మంచి నీటి పారుదల గల లోమ్', ta: 'நல்ல வடிகால் வசதியுள்ள வண்டல் மண்', gu: 'સારી નિકાલવાળી ગોરાડુ માટી', kn: 'ಉತ್ತಮ ನೀರು ಹರಿಯುವ ಲೋಮ್'
    },
    yieldPotential: { 
      en: '20 - 30 tons/hectare', hi: '20 - 30 टन/हेक्टेयर', bn: '২০ - ৩০ টন/হেক্টর', mr: '२० - ३० टन/हेक्टर',
      te: '20 - 30 టన్నులు/హెక్టారు', ta: '20 - 30 டன்/ஹெக்டேர்', gu: '20 - 30 ટન/હેક્ટર', kn: '20 - 30 ಟನ್/ಹೆಕ್ಟೇರ್'
    },
    rotationGroup: 'vegetable'
  },
  {
    id: 'chickpea',
    name: { 
      en: 'Chickpea (Gram)', hi: 'चना', bn: 'ছোলা', mr: 'हरभरा', te: 'శనగలు', ta: 'கொண்டைக்கடலை', gu: 'ચણા', kn: 'ಕಡಲೆ' 
    },
    minPh: 6.0,
    maxPh: 7.5,
    minTemp: 15,
    maxTemp: 30,
    waterRequirement: 'Low',
    sowingMonths: [10, 11],
    description: {
      en: 'High-protein pulse crop that improves soil nitrogen.',
      hi: 'उच्च प्रोटीन वाली दलहन फसल जो मिट्टी के नाइट्रोजन में सुधार करती है।',
      bn: 'উচ্চ প্রোটিনযুক্ত ডাল জাতীয় ফসল যা মাটির নাইট্রোজেন উন্নত করে।',
      mr: 'उच्च प्रथिने असलेले कडधान्य पीक जे मातीतील नायट्रोजन सुधारते.',
      te: 'నేల నత్రజనిని మెరుగుపరిచే అధిక ప్రోటీన్ పప్పుధాన్యాల పంట.',
      ta: 'மண் நைட்ரஜனை மேம்படுத்தும் அதிக புரதச்சத்து கொண்ட பருப்பு வகை பயிர்.',
      gu: 'ઉચ્ચ પ્રોટીન ધરાવતો કઠોળ પાક જે જમીનમાં નાઇટ્રોજન સુધારે છે.',
      kn: 'ಮಣ್ಣಿನ ಸಾರಜನಕವನ್ನು ಸುಧಾರಿಸುವ ಹೆಚ್ಚಿನ ಪ್ರೋಟೀನ್ ದ್ವಿದಳ ಧಾನ್ಯದ ಬೆಳೆ.'
    },
    soilType: { 
      en: 'Sandy Loam to Clay Loam', hi: 'बलुई दोमट से चिकनी दोमट', bn: 'বেলে দোআঁশ থেকে এঁটেল দোআঁশ', mr: 'रेताड लोम ते चिकण लोम माती',
      te: 'ఇసుక లోమ్ నుండి బంకమట్టి లోమ్ వరకు', ta: 'மணல் கலந்த வண்டல் முதல் களிமண் வண்டல் வரை', gu: 'રેતાળ ગોરાડુથી ચીકણી ગોરાડુ માટી', kn: 'ಮರಳು ಮಿಶ್ರಿತ ಲೋಮ್‌ನಿಂದ ಜಿಗುಟು ಲೋಮ್‌ವರೆಗೆ'
    },
    yieldPotential: { 
      en: '1.5 - 2.5 tons/hectare', hi: '1.5 - 2.5 टन/हेक्टेयर', bn: '১.৫ - ২.৫ টন/হেক্টর', mr: '१.५ - २.५ टन/हेक्टर',
      te: '1.5 - 2.5 టన్నులు/హెక్టారు', ta: '1.5 - 2.5 டன்/ஹெக்டேர்', gu: '1.5 - 2.5 ટન/હેક્ટર', kn: '1.5 - 2.5 ಟನ್/ಹೆಕ್ಟೇರ್'
    },
    rotationGroup: 'pulse'
  },
  {
    id: 'soybean',
    name: { 
      en: 'Soybean', hi: 'सोयाबीन', bn: 'সয়াবিন', mr: 'सोयाबीन', te: 'సోయాబీన్', ta: 'சோயாபீன்', gu: 'સોયાબીન', kn: 'ಸೋಯಾಬೀನ್' 
    },
    minPh: 6.0,
    maxPh: 7.0,
    minTemp: 20,
    maxTemp: 35,
    waterRequirement: 'Medium',
    sowingMonths: [6, 7],
    description: {
      en: 'Major oilseed and protein source, excellent for rotation.',
      hi: 'प्रमुख तिलहन और प्रोटीन स्रोत, फसल चक्र के लिए उत्कृष्ट।',
      bn: 'প্রধান তৈলবীজ এবং প্রোটিন উৎস, ফসল চক্রের জন্য চমৎকার।',
      mr: 'प्रमुख तेलबिया आणि प्रೋಟिन स्रोत, पीक फेरपालटासाठी उत्कृष्ट.',
      te: 'ప్రధాన నూనెగింజలు మరియు ప్రోటీన్ వనరు, పంట మార్పిడికి అద్భుతమైనది.',
      ta: 'முக்கிய எண்ணெய் வித்து மற்றும் புரத ஆதாரம், பயிர் சுழற்சிக்கு சிறந்தது.',
      gu: 'મુખ્ય તેલીબિયાં અને પ્રોટીન સ્ત્રોત, પાક ફેરબદલી માટે ઉત્તમ.',
      kn: 'ಪ್ರಮುಖ ಎಣ್ಣೆಕಾಳು ಮತ್ತು ಪ್ರೋಟೀನ್ ಮೂಲ, ಬೆಳೆ ಸರದಿಗೆ ಅತ್ಯುತ್ತಮವಾಗಿದೆ.'
    },
    soilType: { 
      en: 'Well-drained Loam', hi: 'अच्छी जल निकासी वाली दोमट', bn: 'সুনিষ্কাশಿತ দোআঁশ', mr: 'पाण्याचा निचरा होणारी लोम माती',
      te: 'మంచి నీటి పారుదల గల లోమ్', ta: 'நல்ல வடிகால் வசதியுள்ள வண்டல் மண்', gu: 'સારી નિકાલવાળી ગોરાડુ માટી', kn: 'ಉತ್ತಮ ನೀರು ಹರಿಯುವ ಲೋಮ್'
    },
    yieldPotential: { 
      en: '2.0 - 3.0 tons/hectare', hi: '2.0 - 3.0 टन/हेक्टेयर', bn: '২.০ - ৩.০ টন/হেক্টর', mr: '२.० - ३.० टन/हेक्टर',
      te: '2.0 - 3.0 టన్నులు/హెక్టారు', ta: '2.0 - 3.0 டன்/ஹெக்டேர்', gu: '2.0 - 3.0 ટન/હેક્ટર', kn: '2.0 - 3.0 ಟನ್/ಹೆಕ್ಟೇರ್'
    },
    rotationGroup: 'legume'
  },
];

export const TRANSLATIONS: TranslationMap = {
  en: {
    language_name: 'English',
    welcome: 'Welcome to KisanSense',
    soil_intelligence: 'Soil Intelligence',
    crop_advisor: 'Crop Advisor',
    weather_alerts: 'Weather Alerts',
    voice_assistant: 'Voice Assistant',
    check_soil: 'Check My Soil',
    talk_to_ai: 'Talk to AI Bot',
    loading: 'Loading data...',
    location_needed: 'Please enable location access to get local data.',
    error_loading: 'Error loading data',
    retry: 'Retry',
    ph: 'pH',
    soc: 'Organic Carbon',
    dosage: 'Dosage',
    application: 'Application Method',
    treatment_steps: 'Treatment Steps',
    disease_library: 'Disease Library',
    save: 'Save',
    cancel: 'Cancel',
    manual_input: 'Manual Input',
    select_language: 'Select Language',
    home: 'Home',
    soil: 'Soil',
    crops: 'Crops',
    disease: 'Disease',
    weather: 'Weather',
    sand: 'Sand',
    silt: 'Silt',
    clay: 'Clay',
    soil_texture: 'Soil Texture',
    filter: 'Filter',
    severity: 'Severity',
    high: 'High',
    medium: 'Medium',
    low: 'Low',
    select_crops: 'Select Crops',
    select_severity: 'Select Severity',
    clear_all: 'Clear All',
    fungal_risk_title: 'Fungal Risk High',
    fungal_risk_desc: 'Humidity is above 80%. Check crops for signs of fungus.',
    heat_stress_title: 'Heat Stress Alert',
    heat_stress_desc: 'Extreme heat detected or expected. Ensure adequate irrigation.',
    frost_alert_title: 'Frost Alert',
    frost_alert_desc: 'Cold temperatures expected. Protect sensitive crops from frost.',
    heavy_rain_title: 'Heavy Rain Forecast',
    heavy_rain_desc: 'High probability of rain (>70%). Plan field activities accordingly.',
    sowing_window_title: 'Ideal Sowing Window',
    sowing_window_desc: 'Current conditions are perfect for Mustard sowing.',
    rotation_importance_title: 'Why Rotate Crops?',
    rotation_importance_desc: 'Rotating crops prevents soil exhaustion, breaks pest cycles, and naturally improves soil health by balancing nutrient demand.',
    learn_more: 'View Detailed Guide',
    no_previous_data: 'Select your previous crop to get personalized rotation advice.',
    rotation_reason: 'Rotating crops helps break pest cycles and maintains soil health.',
    cereal_benefit: 'Cereals like wheat and rice provide high yields and stable income.',
    legume_benefit: 'Legumes fix nitrogen in the soil, reducing the need for chemical fertilizers.',
    vegetable_benefit: 'Vegetables help in intensive land use and provide quick returns.',
    oilseed_benefit: 'Oilseeds can improve soil structure and provide high-value products.',
    millet_benefit: 'Millets are hardy crops that require less water and improve soil resilience.',
    pulse_benefit: 'Pulses improve soil fertility through nitrogen fixation and are protein-rich.',
    rotation_advice_title: 'Crop Rotation Advisor',
    crop_rotation: 'Crop Rotation Advisor',
    select_previous_crop: 'Select Previous Crop',
    suggested_next: 'Suggested Next Crop',
    all_crops: 'All Crops',
    top_recommendations: 'Top Soil Recommendations',
    soil_match: 'Soil Match',
    forecast_3day: '3-Day Forecast',
    forecast_7day: '7-Day Forecast',
    hourly_forecast: 'Hourly Forecast',
    weekly_forecast: 'Weekly Forecast',
    weather_map: 'Weather Map',
    search_location: 'Search location...',
    no_results: 'No results found',
    use_current_location: 'Use Current Location',
    market: 'Market',
    market_prices: 'Market Prices',
    commodity: 'Commodity',
    price_range: 'Price Range',
    modal_price: 'Modal Price',
    all_states: 'All States',
    select_state: 'Select State',
    search_commodity: 'Search commodity...',
    latest_news: 'Latest Agricultural News',
    read_more: 'Read More',
    compare_crops: 'Compare Crops',
    select_up_to_2: 'Select up to 2 crops to compare',
    yield_potential: 'Yield Potential',
    soil_type: 'Soil Type',
    ph_range: 'pH Range',
    temp_range: 'Temperature Range',
    water_needs: 'Water Needs',
    sowing_time: 'Sowing Time',
    expert_tips: 'Expert Tips',
    view_all: 'View All',
    price_alerts: 'Price Alerts',
    set_alert: 'Set Alert',
    alert_threshold: 'Alert Threshold',
    alert_condition: 'Alert Condition',
    above: 'Above',
    below: 'Below',
    alert_created: 'Price alert created!',
    no_alerts: 'No active price alerts',
    notify_me: 'Notify me when price is',
  },
  hi: {
    language_name: 'हिंदी',
    welcome: 'किसानसेंस में आपका स्वागत है',
    soil_intelligence: 'मिट्टी की जानकारी',
    crop_advisor: 'फसल सलाहकार',
    weather_alerts: 'मौसम की चेतावनी',
    voice_assistant: 'वॉयस असिस्टेंट',
    check_soil: 'मेरी मिट्टी की जाँच करें',
    talk_to_ai: 'एआई बॉट से बात करें',
    loading: 'डेटा लोड हो रहा है...',
    location_needed: 'स्थानीय डेटा प्राप्त करने के लिए कृपया स्थान पहुंच की अनुमति दें।',
    error_loading: 'डेटा लोड करने में त्रुटि',
    retry: 'पुनः प्रयास करें',
    ph: 'pH',
    soc: 'जैविक कार्बन',
    dosage: 'खुराक',
    application: 'आवेदन विधि',
    treatment_steps: 'उपचार कदम',
    disease_library: 'रोग पुस्तकालय',
    save: 'सहेजें',
    cancel: 'रद्द करें',
    manual_input: 'मैनुअल इनपुट',
    select_language: 'भाषा का चयन करें',
    home: 'होम',
    soil: 'मिट्टी',
    crops: 'फसल',
    disease: 'रोग',
    weather: 'मौसम',
    sand: 'रेत',
    silt: 'सिल्ट',
    clay: 'चिकनी मिट्टी',
    soil_texture: 'मिट्टी की बनावट',
    filter: 'फ़िल्टर',
    severity: 'गंभीरता',
    high: 'उच्च',
    medium: 'मध्यम',
    low: 'कम',
    select_crops: 'फसलें चुनें',
    select_severity: 'गंभीरता चुनें',
    clear_all: 'सभी साफ़ करें',
    fungal_risk_title: 'कवक का उच्च जोखिम',
    fungal_risk_desc: 'आर्द्रता 80% से ऊपर है। कवक के संकेतों के लिए फसलों की जाँच करें।',
    heat_stress_title: 'गर्मी का तनाव अलर्ट',
    heat_stress_desc: 'अत्यधिक गर्मी का पता चला या अपेक्षित है। पर्याप्त सिंचाई सुनिश्चित करें।',
    frost_alert_title: 'पाले की चेतावनी',
    frost_alert_desc: 'ठंडे तापमान की संभावना। संवेदनशील फसलों को पाले से बचाएं।',
    heavy_rain_title: 'भारी बारिश का पूर्वानुमान',
    heavy_rain_desc: 'बारिश की उच्च संभावना (>70%)। तदनुसार कृषि गतिविधियों की योजना बनाएं।',
    sowing_window_title: 'बुवाई के लिए आदर्श समय',
    sowing_window_desc: 'वर्तमान परिस्थितियां सरसों की बुवाई के लिए उपयुक्त हैं।',
    rotation_importance_title: 'फसल चक्र क्यों महत्वपूर्ण है?',
    rotation_importance_desc: 'फसल चक्र मिट्टी की उर्वरता बनाए रखने, कीटों और रोगों को कम करने और विभिन्न प्रकार की फसलों को बदलकर मिट्टी की संरचना में सुधार करने में मदद करता है।',
    learn_more: 'विस्तृत गाइड देखें',
    no_previous_data: 'व्यक्तिगत फसल चक्र सलाह प्राप्त करने के लिए अपनी पिछली फसल चुनें।',
    cereal_benefit: 'गेहूं और चावल जैसे अनाज उच्च उपज और स्थिर आय प्रदान करते हैं।',
    legume_benefit: 'दलहन मिट्टी में नाइट्रोजन को स्थिर करते हैं, जिससे रासायनिक उर्वरकों की आवश्यकता कम हो जाती है।',
    rotation_reason: 'फसल चक्र कीट चक्र को तोड़ने और मिट्टी के स्वास्थ्य को बनाए रखने में मदद करता है।',
    vegetable_benefit: 'सब्जियां गहन भूमि उपयोग में मदद करती हैं और त्वरित लाभ प्रदान करती हैं।',
    oilseed_benefit: 'तिलहन मिट्टी की संरचना में सुधार कर सकते हैं और उच्च मूल्य वाले उत्पाद प्रदान करते हैं।',
    millet_benefit: 'बाजरा कठोर फसलें हैं जिन्हें कम पानी की आवश्यकता होती है और मिट्टी के लचीलेपन में सुधार करती हैं।',
    pulse_benefit: 'दलहन नाइट्रोजन स्थिरीकरण के माध्यम से मिट्टी की उर्वरता में सुधार करते हैं और प्रोटीन से भरपूर होते हैं।',
    rotation_advice_title: 'फसल चक्र सलाहकार',
    crop_rotation: 'फसल चक्र सलाहकार',
    select_previous_crop: 'पिछली फसल चुनें',
    suggested_next: 'सुझाई गई अगली फसल',
    all_crops: 'सभी फसलें',
    top_recommendations: 'शीर्ष मिट्टी की सिफारिशें',
    soil_match: 'मिट्टी का मिलान',
    forecast_3day: '3-दिवसीय पूर्वानुमान',
    forecast_7day: '7-दिवसीय पूर्वानुमान',
    hourly_forecast: 'प्रति घंटा पूर्वानुमान',
    weekly_forecast: 'साप्ताहिक पूर्वानुमान',
    weather_map: 'मौसम मानचित्र',
    all_states: 'सभी राज्य',
    select_state: 'राज्य चुनें',
    search_location: 'स्थान खोजें...',
    no_results: 'कोई परिणाम नहीं मिला',
    use_current_location: 'वर्तमान स्थान का उपयोग करें',
    latest_news: 'नवीनतम कृषि समाचार',
    read_more: 'अधिक पढ़ें',
    compare_crops: 'फसलों की तुलना करें',
    select_up_to_2: 'तुलना करने के लिए अधिकतम 2 फसलें चुनें',
    yield_potential: 'उपज क्षमता',
    soil_type: 'मिट्टी का प्रकार',
    ph_range: 'pH रेंज',
    temp_range: 'तापमान रेंज',
    water_needs: 'पानी की आवश्यकता',
    sowing_time: 'बुवाई का समय',
    expert_tips: 'विशेषज्ञ युक्तियाँ',
    view_all: 'सभी देखें',
    price_alerts: 'मूल्य अलर्ट',
    set_alert: 'अलर्ट सेट करें',
    alert_threshold: 'अलर्ट सीमा',
    alert_condition: 'अलर्ट स्थिति',
    above: 'ऊपर',
    below: 'नीचे',
    alert_created: 'मूल्य अलर्ट बनाया गया!',
    no_alerts: 'कोई सक्रिय मूल्य अलर्ट नहीं',
    notify_me: 'मुझे सूचित करें जब मूल्य हो',
  },
  bn: {
    language_name: 'বাংলা',
    welcome: 'কিসানসেন্সে স্বাগতম',
    soil_intelligence: 'মাটির বুদ্ধিমত্তা',
    crop_advisor: 'ফসল উপদেষ্টা',
    weather_alerts: 'আবহাওয়া সতর্কতা',
    voice_assistant: 'ভয়েস সহায়ক',
    check_soil: 'আমার মাটি পরীক্ষা করুন',
    talk_to_ai: 'AI বট এর সাথে কথা বলুন',
    loading: 'ডেটা লোড হচ্ছে...',
    location_needed: 'স্থানীয় ডেটা পেতে দয়া করে অবস্থান অ্যাক্সেস সক্ষম করুন।',
    error_loading: 'ডেটা লোড করতে ত্রুটি',
    retry: 'পুনরায় চেষ্টা করুন',
    ph: 'pH',
    soc: 'জৈব কার্বন',
    dosage: 'মাত্রা',
    application: 'তরীকার প্রয়োগ',
    treatment_steps: 'চিকিৎসা পদক্ষেপ',
    disease_library: 'রোগ লাইব্রেরি',
    save: 'সংরক্ষণ করুন',
    cancel: 'বাতিল করুন',
    manual_input: 'ম্যানুয়াল ইনপুট',
    select_language: 'ভাষা নির্বাচন করুন',
    home: 'হোম',
    soil: 'মাটি',
    crops: 'ফসল',
    disease: 'রোগ',
    weather: 'আবহাওয়া',
    sand: 'বালি',
    silt: 'পলি',
    clay: 'কাদা',
    soil_texture: 'মাটির গঠন',
    filter: 'ফিল্টার',
    severity: 'তীব্রতা',
    high: 'উচ্চ',
    medium: 'মাঝারি',
    low: 'নিম্ন',
    select_crops: 'শস্য নির্বাচন করুন',
    select_severity: 'তীব্রতা নির্বাচন করুন',
    clear_all: 'সব মুছে ফেলুন',
    fungal_risk_title: 'ছত্রাক সংক্রমণের উচ্চ ঝুঁকি',
    fungal_risk_desc: 'আর্দ্রতা ৮০% এর বেশি। ছত্রাকের লক্ষণের জন্য ফসল পরীক্ষা করুন।',
    heat_stress_title: 'অত্যধিক তাপের সতর্কতা',
    heat_stress_desc: 'অত্যধিক তাপ শনাক্ত করা হয়েছে বা প্রত্যাশিত। পর্যাপ্ত সেচ নিশ্চিত করুন।',
    frost_alert_title: 'তুষারপাতের সতর্কতা',
    frost_alert_desc: 'ঠান্ডা তাপমাত্রা প্রত্যাশিত। সংবেদনশীল ফসল তুষারপাত থেকে রক্ষা করুন।',
    heavy_rain_title: 'ভারী বৃষ্টির পূর্বাভাস',
    heavy_rain_desc: 'বৃষ্টির উচ্চ সম্ভাবনা (>৭০%)। সেই অনুযায়ী কৃষি কার্যক্রম পরিকল্পনা করুন।',
    sowing_window_title: 'বপনের আদর্শ সময়',
    sowing_window_desc: 'বর্তমান পরিস্থিতি সরিষা বপনের জন্য উপযুক্ত।',
    rotation_importance_title: 'ফসল আবর্তন কেন গুরুত্বপূর্ণ?',
    rotation_importance_desc: 'ফসল আবর্তন মাটির উর্বরতা বজায় রাখতে সাহায্য করে, কীটপতঙ্গ ও রোগ কমায় এবং মাটির গঠন উন্নত করে।',
    learn_more: 'বিস্তারিত নির্দেশিকা দেখুন',
    no_previous_data: 'ব্যক্তিগতকৃত আবর্তন পরামর্শ পেতে আপনার আগের ফসল নির্বাচন করুন।',
    cereal_benefit: 'গম এবং ধানের মতো শস্য উচ্চ ফলন এবং স্থিতিশীল আয় প্রদান করে।',
    legume_benefit: 'শিম্বগোত্রীয় ফসল মাটিতে নাইট্রোজেন স্থির করে, রাসায়নিক সারের প্রয়োজনীয়তা কমায়।',
    rotation_reason: 'আপনার আগের ফসলের উপর ভিত্তি করে, এই আবর্তন মাটির স্বাস্থ্যকে সর্বোচ্চ করবে।',
    rotation_advice_title: 'ফসল আবর্তন উপদেষ্টা',
    crop_rotation: 'ফসল আবর্তন উপদেষ্টা',
    select_previous_crop: 'আগের ফসল নির্বাচন করুন',
    suggested_next: 'প্রস্তাবিত পরবর্তী ফসল',
    all_crops: 'সমস্ত ফসল',
    top_recommendations: 'শীর্ষ মাটির সুপারিশ',
    soil_match: 'মাটির মিল',
    forecast_3day: '৩-দিনের পূর্বাভাস',
    forecast_7day: '৭-দিনের পূর্বাভাস',
    hourly_forecast: 'প্রতি ঘণ্টার পূর্বাভাস',
    weekly_forecast: 'সাপ্তাহিক পূর্বাভাস',
    weather_map: 'আবহাওয়ার মানচিত্র',
    all_states: 'সমস্ত রাজ্য',
    select_state: 'রাজ্য নির্বাচন করুন',
    search_location: 'স্থান অনুসন্ধান করুন...',
    no_results: 'কোন ফলাফল পাওয়া যায়নি',
    use_current_location: 'বর্তমান অবস্থান ব্যবহার করুন',
    latest_news: 'সর্বশেষ কৃষি সংবাদ',
    read_more: 'আরও পড়ুন',
    compare_crops: 'ফসলের তুলনা করুন',
    select_up_to_2: 'তুলনা করতে সর্বোচ্চ ২টি ফসল নির্বাচন করুন',
    yield_potential: 'ফলন সম্ভাবনা',
    soil_type: 'মাটির ধরন',
    ph_range: 'pH পরিসীমা',
    temp_range: 'তাপমাত্রা পরিসীমা',
    water_needs: 'জলের প্রয়োজন',
    sowing_time: 'বপনের সময়',
    expert_tips: 'বিশেষজ্ঞের পরামর্শ',
    view_all: 'সব দেখুন',
    price_alerts: 'মূল্য সতর্কতা',
    set_alert: 'সতর্কতা সেট করুন',
    alert_threshold: 'সতর্কতা সীমা',
    alert_condition: 'সতর্কতা শর্ত',
    above: 'উপরে',
    below: 'নিচে',
    alert_created: 'মূল্য সতর্কতা তৈরি করা হয়েছে!',
    no_alerts: 'কোনো সক্রিয় মূল্য সতর্কতা নেই',
    notify_me: 'আমাকে জানান যখন মূল্য হবে',
  },
  mr: {
    language_name: 'मराठी',
    welcome: 'किसानसेन्सला स्वागत आहे',
    soil_intelligence: 'मातीची बुद्धिमत्ता',
    crop_advisor: 'पीक सल्लागार',
    weather_alerts: 'हवामान सतर्कता',
    voice_assistant: 'व्हॉयस सहायक',
    check_soil: 'माझी माती तपासा',
    talk_to_ai: 'AI बॉटशी बात करा',
    loading: 'डेटा लोड होत आहे...',
    location_needed: 'स्थानीय डेटा मिळविण्यासाठी कृपया स्थान प्रवेश सक्षम करा।',
    error_loading: 'डेटा लोड करताना त्रुटी',
    retry: 'पुन्हा प्रयत्न करा',
    ph: 'pH',
    soc: 'जैविक कार्बन',
    dosage: 'मात्रा',
    application: 'अर्ज पद्धति',
    treatment_steps: 'उपचार पायरी',
    disease_library: 'रोग लायब्ररी',
    save: 'जतन करा',
    cancel: 'रद्द करा',
    manual_input: 'व्यक्तिगत इनपुट',
    select_language: 'भाषा निवडा',
    home: 'होम',
    soil: 'माती',
    crops: 'पीक',
    disease: 'रोग',
    weather: 'हवामान',
    sand: 'वाळू',
    silt: 'गाळ',
    clay: 'चिकणमाती',
    soil_texture: 'मातीचा पोत',
    filter: 'फिल्टर',
    severity: 'तीव्रता',
    high: 'उच्च',
    medium: 'मध्यम',
    low: 'कमी',
    select_crops: 'पिके निवडा',
    select_severity: 'तीव्रता निवडा',
    clear_all: 'सर्व साफ करा',
    fungal_risk_title: 'बुरशीचा धोका जास्त',
    fungal_risk_desc: 'आर्द्रता ८०% पेक्षा जास्त आहे. पिकांवर बुरशीची लक्षणे तपासा.',
    heat_stress_title: 'उष्णतेचा ताण अलर्ट',
    heat_stress_desc: 'अत्यधिक उष्णता आढळली किंवा अपेक्षित आहे. पुरेशी सिंचन व्यवस्था करा.',
    frost_alert_title: 'थंडीची लाट सतर्कता',
    frost_alert_desc: 'कमी तापमानाची शक्यता. संवेदनशील पिकांचे थंडीपासून संरक्षण करा.',
    heavy_rain_title: 'मुसळधार पावसाचा अंदाज',
    heavy_rain_desc: 'पावसाची दाट शक्यता (>७०%). त्यानुसार शेतीकामाचे नियोजन करा.',
    sowing_window_title: 'पेरणीसाठी आदर्श वेळ',
    sowing_window_desc: 'सध्याची परिस्थिती मोहरीच्या पेरणीसाठी योग्य आहे.',
    rotation_importance_title: 'पीक फेरपालट का महत्त्वाची आहे?',
    rotation_importance_desc: 'पीक फेरपालट केल्याने जमिनीचा कस टिकून राहतो, कीड आणि रोगांचे प्रमाण कमी होते आणि जमिनीचे आरोग्य सुधारते.',
    learn_more: 'सविस्तर मार्गदर्शक पहा',
    no_previous_data: 'वैयक्तिकृत पीक फेरपालट सल्ला मिळविण्यासाठी तुमचे मागील पीक निवडा।',
    cereal_benefit: 'गहू आणि तांदूळ यांसारखी तृणधान्ये उच्च उत्पन्न आणि स्थिर उत्पन्न देतात।',
    legume_benefit: 'कडधान्ये जमिनीत नायट्रोजन स्थिर करतात, ज्यामुळे रासायनिक खतांची गरज कमी होते।',
    rotation_reason: 'तुमच्या मागील पिकावर आधारित, ही फेरपालट जमिनीचे आरोग्य वाढवेल।',
    rotation_advice_title: 'पीक फेरपालट सल्लागार',
    crop_rotation: 'पीक फेरपालट सल्लागार',
    select_previous_crop: 'मागील पीक निवडा',
    suggested_next: 'सुचवलेले पुढील पीक',
    all_crops: 'सर्व पिके',
    top_recommendations: 'शीर्ष मिट्टी की सिफारिशें',
    soil_match: 'मिट्टी का मिलान',
    forecast_3day: '३-दिवसीय अंदाज',
    forecast_7day: '७-दिवसीय अंदाज',
    hourly_forecast: 'तासाभराचा अंदाज',
    weekly_forecast: 'साप्ताहिक अंदाज',
    weather_map: 'हवामान नकाशा',
    all_states: 'सर्व राज्ये',
    select_state: 'राज्य निवडा',
    search_location: 'स्थान शोधा...',
    no_results: 'निकाल सापडले नाहीत',
    use_current_location: 'वर्तमान स्थान वापरा',
    latest_news: 'नवीनतम कृषी बातम्या',
    read_more: 'अधिक वाचा',
    compare_crops: 'पिकांची तुलना करा',
    select_up_to_2: 'तुलना करण्यासाठी जास्तीत जास्त २ पिके निवडा',
    yield_potential: 'उत्पादन क्षमता',
    soil_type: 'मातीचा प्रकार',
    ph_range: 'pH श्रेणी',
    temp_range: 'तापमान श्रेणी',
    water_needs: 'पाण्याची गरज',
    sowing_time: 'पेरणीची वेळ',
    expert_tips: 'तज्ज्ञांचे सल्ले',
    view_all: 'सर्व पहा',
    price_alerts: 'किंमत अलर्ट',
    set_alert: 'अलर्ट सेट करा',
    alert_threshold: 'अलर्ट मर्यादा',
    alert_condition: 'अलर्ट स्थिती',
    above: 'वर',
    below: 'खाली',
    alert_created: 'किंमत अलर्ट तयार केला!',
    no_alerts: 'कोणतेही सक्रिय किंमत अलर्ट नाहीत',
    notify_me: 'जेव्हा किंमत असेल तेव्हा मला कळवा',
  },
  te: {
    language_name: 'తెలుగు',
    welcome: 'కిసానసేన్స్‌కు స్వాగతం',
    soil_intelligence: 'మట్టి గుణాలు',
    crop_advisor: 'వరుస సలహాదారు',
    weather_alerts: 'వాతావరణ హెచ్చరికలు',
    voice_assistant: 'వాయిస్ సహాయ్యకుడు',
    check_soil: 'నా మట్టిని చెక్ చేయండి',
    talk_to_ai: 'AI బాట్‌తో చాట్ చేయండి',
    loading: 'డేటా లోడ్ అవుతోంది...',
    location_needed: 'స్థానిక డేటా కోసం దయచేసి స్థానాన్ని ఉపయోగించు.',
    error_loading: 'డేటా లోడ్ చేయడంలో లోపం',
    retry: 'మళ్ళీ ప్రయత్నించండి',
    ph: 'pH',
    soc: 'సేంద్రీయ కార్బన్',
    dosage: 'మోతాదు',
    application: 'అన్వయం',
    treatment_steps: 'చికిత్స సోపానాలు',
    disease_library: 'వ్యాధుల లైబ్రరీ',
    save: 'సేవ్ చేయండి',
    cancel: 'రద్దు చేయండి',
    manual_input: 'హస్తపూర్ణ ఇన్‌పుట్',
    select_language: 'భాషను ఎంచుకోండి',
    home: 'హోమ్',
    soil: 'మట్టి',
    crops: 'పంటలు',
    disease: 'వ్యాధి',
    weather: 'వాతావరణం',
    sand: 'ఇసుక',
    silt: 'సిల్ట్',
    clay: 'బంకమట్టి',
    soil_texture: 'మట్టి ఆకృతి',
    filter: 'ఫిల్టర్',
    severity: 'తీవ్రత',
    high: 'ఎక్కువ',
    medium: 'మధ్యస్థం',
    low: 'తక్కువ',
    all_states: 'అన్ని రాష్ట్రాలు',
    select_state: 'రాష్ట్రాన్ని ఎంచుకోండి',
    select_crops: 'పంటలను ఎంచుకోండి',
    select_severity: 'తీవ్రతను ఎంచుకోండి',
    clear_all: 'అన్నీ తొలగించు',
    fungal_risk_title: 'శిలీంధ్రాల ముప్పు ఎక్కువ',
    fungal_risk_desc: 'తేమ 80% కంటే ఎక్కువగా ఉంది. పంటలను శిలీంధ్రాల కోసం తనిఖీ చేయండి.',
    heat_stress_title: 'అధిక ఉష్ణోగ్రత హెచ్చరిక',
    heat_stress_desc: 'అధిక ఉష్ణోగ్రత గుర్తించబడింది లేదా అంచనా వేయబడింది. తగినంత నీటి పారుదలని నిర్ధారించుకోండి.',
    frost_alert_title: 'మంచు హెచ్చరిక',
    frost_alert_desc: 'తక్కువ ఉష్ణోగ్రతలు అంచనా వేయబడ్డాయి. సున్నితమైన పంటలను మంచు నుండి రక్షించండి.',
    heavy_rain_title: 'భారీ వర్ష సూచన',
    heavy_rain_desc: 'వర్షం పడే అవకాశం ఎక్కువగా ఉంది (>70%). తదనుగుణంగా వ్యవసాయ పనులను ప్లాన్ చేయండి.',
    sowing_window_title: 'విత్తడానికి అనుకూల సమయం',
    sowing_window_desc: 'ప్రస్తుత పరిస్థితులు ఆవాలు విత్తడానికి అనుకూలంగా ఉన్నాయి.',
    rotation_importance_title: 'పంట మార్పిడి ఎందుకు ముఖ్యం?',
    rotation_importance_desc: 'పంట మార్పిడి మట్టి సారాన్ని కాపాడుతుంది, చీడపీడల ప్రభావాన్ని తగ్గిస్తుంది మరియు నేల ఆరోగ్యాన్ని మెరుగుపరుస్తుంది.',
    learn_more: 'వివరమైన గైడ్‌ను చూడండి',
    no_previous_data: 'వ్యక్తిగతీకరించిన పంట మార్పిడి సలహా పొందడానికి మీ మునుపటి పంటను ఎంచుకోండి.',
    cereal_benefit: 'గోధుమలు మరియు వరి వంటి తృణధాన్యాలు అధిక దిగుబడిని మరియు స్థిరమైన ఆదాయాన్ని అందిస్తాయి.',
    legume_benefit: 'పప్పుధాన్యాలు నేలలో నత్రజనిని స్థిరీకరిస్తాయి, రసాయన ఎరువుల అవసరాన్ని తగ్గిస్తాయి.',
    rotation_reason: 'మీ మునుపటి పంట ఆధారంగా, ఈ మార్పిడి నేల ఆరోగ్యాన్ని పెంచుతుంది.',
    rotation_advice_title: 'పంట మార్పిడి సలహాదారు',
    crop_rotation: 'పంట మార్పిడి సలహాదారు',
    select_previous_crop: 'మునుపటి పంటను ఎంచుకోండి',
    suggested_next: 'ప్రతిపాదించిన తదుపరి పంట',
    all_crops: 'అన్ని పంటలు',
    top_recommendations: 'టాప్ మట్టి సిఫార్సులు',
    soil_match: 'మట్టి సరిపోలిక',
    forecast_3day: '3-రోజుల అంచనా',
    forecast_7day: '7-రోజుల అంచనా',
    hourly_forecast: 'గంటల వారీ అంచనా',
    weekly_forecast: 'వారపు అంచనా',
    weather_map: 'వాతావరణ పటం',
    search_location: 'స్థానాన్ని శోధించండి...',
    no_results: 'ఫలితాలు ఏవీ లేవు',
    use_current_location: 'ప్రస్తుత స్థానాన్ని ఉపయోగించండి',
    latest_news: 'తాజా వ్యవసాయ వార్తలు',
    read_more: 'మరింత చదవండి',
    compare_crops: 'పంటల పోలిక',
    select_up_to_2: 'పోల్చడానికి గరిష్టంగా 2 పంటలను ఎంచుకోండి',
    yield_potential: 'దిగుబడి సామర్థ్యం',
    soil_type: 'నేల రకం',
    ph_range: 'pH పరిధి',
    temp_range: 'ఉష్ణోగ్రత పరిధి',
    water_needs: 'నీటి అవసరాలు',
    sowing_time: 'విత్తే సమయం',
    expert_tips: 'నిపుణుల సూచనలు',
    view_all: 'అన్నీ చూడండి',
    price_alerts: 'ధర హెచ్చరికలు',
    set_alert: 'హెచ్చరికను సెట్ చేయండి',
    alert_threshold: 'హెచ్చరిక పరిమితి',
    alert_condition: 'హెచ్చరిక పరిస్థితి',
    above: 'పైన',
    below: 'క్రింద',
    alert_created: 'ధర హెచ్చరిక సృష్టించబడింది!',
    no_alerts: 'క్రియాశీల ధర హెచ్చరికలు లేవు',
    notify_me: 'ధర ఇలా ఉన్నప్పుడు నాకు తెలియజేయండి',
  },
  ta: {
    language_name: 'தமிழ்',
    welcome: 'கிசான்சென்ஸிற்கு வரவேற்கிறோம்',
    soil_intelligence: 'மண் புத்திமை',
    crop_advisor: 'பயிர் ஆலோசகர்',
    weather_alerts: 'வானிலை எச்சரிக்கைகள்',
    voice_assistant: 'குரல் உதவியாளர்',
    check_soil: 'எனது மண்ணைச் சரிபார்க்கவும்',
    talk_to_ai: 'AI பாட்டிடம் பேசவும்',
    loading: 'தரவு ஏற்றப்படுகிறது...',
    location_needed: 'உள்ளூர் தரவைப் பெற இருப்பிட அணுகலை அனுமதிக்கவும்।',
    error_loading: 'தரவு ஏற்றுவதில் பிழை',
    retry: 'மீண்டும் முயற்சிக்கவும்',
    ph: 'pH',
    soc: 'கரிம கார்பன்',
    dosage: 'அளவு',
    application: 'பயன்பாடு முறை',
    treatment_steps: 'சிகிச்சை படிகள்',
    disease_library: 'நோய் நூலகம்',
    save: 'சேமிக்கவும்',
    cancel: 'ரத்து செய்யவும்',
    manual_input: 'கைமுறை உள்ளீடு',
    select_language: 'மொழியைத் தேர்ந்தெடுக்கவும்',
    home: 'முகப்பு',
    soil: 'மண்',
    crops: 'பயிர்கள்',
    disease: 'நோய்',
    weather: 'வானிலை',
    sand: 'மணல்',
    silt: 'வண்டல்',
    clay: 'களிமண்',
    soil_texture: 'மண் அமைப்பு',
    filter: 'வடிகட்டி',
    severity: 'தீவிரம்',
    high: 'அதிகம்',
    medium: 'நடுத்தரம்',
    low: 'குறைவு',
    select_crops: 'பயிர்களைத் தேர்ந்தெடுக்கவும்',
    select_severity: 'தீவிரத்தைத் தேர்ந்தெடுக்கவும்',
    clear_all: 'அனைத்தையும் நீக்கு',
    fungal_risk_title: 'பூஞ்சை பாதிப்பு அதிகம்',
    fungal_risk_desc: 'ஈரப்பதம் 80% க்கும் அதிகமாக உள்ளது. பயிர்களில் பூஞ்சை அறிகுறிகளைச் சரிபார்க்கவும்.',
    heat_stress_title: 'வெப்ப அழுத்த எச்சரிக்கை',
    heat_stress_desc: 'அதிக வெப்பம் கண்டறியப்பட்டுள்ளது அல்லது எதிர்பார்க்கப்படுகிறது. போதுமான நீர்ப்பாசனத்தை உறுதிப்படுத்தவும்.',
    frost_alert_title: 'பனிப்பொழிவு எச்சரிக்கை',
    frost_alert_desc: 'குறைந்த வெப்பநிலை எதிர்பார்க்கப்படுகிறது. உணர்திறன் கொண்ட பயிர்களைப் பனியிலிருந்து பாதுகாக்கவும்.',
    heavy_rain_title: 'கனமழை முன்னறிவிப்பு',
    heavy_rain_desc: 'மழை பெய்ய அதிக வாய்ப்பு (>70%). அதற்கேற்ப விவசாயப் பணிகளைத் திட்டமிடுங்கள்.',
    sowing_window_title: 'விதைப்பதற்கு ஏற்ற காலம்',
    sowing_window_desc: 'தற்போதைய நிலை கடுகு விதைப்பதற்கு ஏற்றதாக உள்ளது.',
    rotation_importance_title: 'பயிர் சுழற்சி ஏன் முக்கியம்?',
    rotation_importance_desc: 'பயிர் சுழற்சி மண்ணின் வளத்தைப் பாதுகாக்கவும், பூச்சிகள் மற்றும் நோய்களைக் குறைக்கவும், மண்ணின் ஆரோக்கியத்தை மேம்படுத்தவும் உதவுகிறது.',
    learn_more: 'விரிவான வழிகாட்டியைப் பார்க்கவும்',
    no_previous_data: 'தனிப்பயனாக்கப்பட்ட சுழற்சி ஆலோசனையைப் பெற உங்கள் முந்தைய பயிரைத் தேர்ந்தெடுக்கவும்.',
    cereal_benefit: 'கோதுமை மற்றும் அரிசி போன்ற தானியங்கள் அதிக மகசூல் மற்றும் நிலையான வருமானத்தை வழங்குகின்றன.',
    legume_benefit: 'பருப்பு வகைகள் மண்ணில் நைட்ரஜனை நிலைநிறுத்துகின்றன, இரசாயன உரங்களின் தேவையைக் குறைக்கின்றன.',
    rotation_reason: 'உங்கள் முந்தைய பயிரின் அடிப்படையில், இந்த சுழற்சி மண்ணின் ஆரோக்கியத்தை மேம்படுத்தும்.',
    rotation_advice_title: 'பயிர் சுழற்சி ஆலோசகர்',
    crop_rotation: 'பயிர் சுழற்சி ஆலோசகர்',
    select_previous_crop: 'முந்தைய பயிரைத் தேர்ந்தெடுக்கவும்',
    suggested_next: 'பரிந்துரைக்கப்பட்ட அடுத்த பயிர்',
    all_crops: 'அனைத்துப் பயிர்கள்',
    top_recommendations: 'சிறந்த மண் பரிந்துரைகள்',
    soil_match: 'மண் பொருத்தம்',
    forecast_3day: '3-நாள் முன்னறிவிப்பு',
    forecast_7day: '7-நாள் முன்னறிவிப்பு',
    hourly_forecast: 'மணிநேர முன்னறிவிப்பு',
    weekly_forecast: 'வாராந்திர முன்னறிவிப்பு',
    weather_map: 'வானிலை வரைபடம்',
    search_location: 'இருப்பிடத்தைத் தேடுங்கள்...',
    no_results: 'முடிவுகள் எதுவும் இல்லை',
    use_current_location: 'தற்போதைய இருப்பிடத்தைப் பயன்படுத்தவும்',
    latest_news: 'சமீபத்திய விவசாய செய்திகள்',
    read_more: 'மேலும் படிக்க',
    compare_crops: 'பயிர்களை ஒப்பிடுக',
    select_up_to_2: 'ஒப்பிட அதிகபட்சம் 2 பயிர்களைத் தேர்ந்தெடுக்கவும்',
    yield_potential: 'மகசூல் திறன்',
    soil_type: 'மண் வகை',
    ph_range: 'pH வரம்பு',
    temp_range: 'வெப்பநிலை வரம்பு',
    water_needs: 'நீர் தேவைகள்',
    sowing_time: 'விதைப்பு நேரம்',
    expert_tips: 'நிபுணர் குறிப்புகள்',
    view_all: 'அனைத்தையும் காண்க',
    price_alerts: 'விலை எச்சரிக்கைகள்',
    set_alert: 'எச்சரிக்கையை அமை',
    alert_threshold: 'எச்சரிக்கை வரம்பு',
    alert_condition: 'எச்சரிக்கை நிலை',
    above: 'மேலே',
    below: 'கீழே',
    alert_created: 'விலை எச்சரிக்கை உருவாக்கப்பட்டது!',
    no_alerts: 'செயலில் உள்ள விலை எச்சரிக்கைகள் இல்லை',
    notify_me: 'விலை இவ்வாறு இருக்கும்போது எனக்கு அறிவிக்கவும்',
  },
  gu: {
    language_name: 'ગુજરાતી',
    welcome: 'કિસાનસેન્સમાં તમારું સ્વાગત છે',
    soil_intelligence: 'જમીનની બુદ્ધિ',
    crop_advisor: 'પાક સલાહકાર',
    weather_alerts: 'હવામાન ચેતવણીઓ',
    voice_assistant: 'વોઇસ સહાયક',
    check_soil: 'મેરી જમીન તપાસો',
    talk_to_ai: 'AI બોટ સાથે વાત કરો',
    loading: 'ડેટા લોડ થઇ રહ્યો છે...',
    location_needed: 'સ્થાનીય ડેટા માટે કૃપયા સ્થાન અંગત સક્ષમ કરો।',
    error_loading: 'ડેટા લોડ કરવામાં ભૂલ',
    retry: 'ફરીથી પ્રયાસ કરો',
    ph: 'pH',
    soc: 'સાંદ્ર્યુક્ત કાર્બન',
    dosage: 'માત્રા',
    application: 'આવેદન પદ્ધતિ',
    treatment_steps: 'સારવાર પગલાં',
    disease_library: 'રોગ પુસ્તકાલય',
    save: 'સાચવો',
    cancel: 'રદ્દ કરો',
    manual_input: 'હાથથી ઇનપુટ',
    select_language: 'ભાષા પસંદ કરો',
    home: 'હોમ',
    soil: 'જમીન',
    crops: 'પાક',
    disease: 'રોગ',
    weather: 'હવામાન',
    sand: 'રેતી',
    silt: 'કાંપ',
    clay: 'માટી',
    soil_texture: 'જમીનનું બંધારણ',
    filter: 'ફિલ્ટર',
    severity: 'તીવ્રતા',
    high: 'ઉચ્ચ',
    medium: 'મધ્યમ',
    low: 'ઓછી',
    select_crops: 'પાક પસંદ કરો',
    select_severity: 'તીવ્રતા પસંદ કરો',
    clear_all: 'બધું સાફ કરો',
    fungal_risk_title: 'ફૂગનું જોખમ વધારે',
    fungal_risk_desc: 'ભેજ 80% થી વધુ છે. પાકમાં ફૂગના ચિહ્નો તપાસો.',
    heat_stress_title: 'ગરમીના તણાવની ચેતવણી',
    heat_stress_desc: 'અતિશય ગરમી જોવા મળી છે અથવા અપેક્ષિત છે. પૂરતી સિંચાઈની ખાતરી કરો.',
    frost_alert_title: 'ઝાકળની ચેતવણી',
    frost_alert_desc: 'ઠંડું તાપમાન અપેક્ષિત છે. સંવેદનશીલ પાકને ઝાકળથી બચાવો.',
    heavy_rain_title: 'ભારે વરસાદની આગાહી',
    heavy_rain_desc: 'વરસાદની ઉચ્ચ સંભાવના (>70%). તે મુજબ ખેતીની પ્રવૃત્તિઓનું આયોજન કરો.',
    sowing_window_title: 'વાવણી માટે આદર્શ સમય',
    sowing_window_desc: 'વર્તમાન પરિસ્થિતિ રાયડાની વાવણી માટે યોગ્ય છે.',
    rotation_importance_title: 'પાક ફેરબદલી કેમ મહત્વની છે?',
    rotation_importance_desc: 'પાક ફેરબદલી જમીનની ફળદ્રુપતા જાળવી રાખવામાં, જીવાત અને રોગો ઘટાડવામાં અને જમીનનું સ્વાસ્થ્ય સુધારવામાં મદદ કરે છે.',
    learn_more: 'વિગતવાર માર્ગદર્શિકા જુઓ',
    no_previous_data: 'વ્યક્તિગત પાક ફેરબદલી સલાહ મેળવવા માટે તમારો પાછલો પાક પસંદ કરો.',
    cereal_benefit: 'ઘઉં અને ચોખા જેવા અનાજ ઉચ્ચ ઉપજ અને સ્થિર આવક આપે છે.',
    legume_benefit: 'કઠોળ જમીનમાં નાઇટ્રોજન સ્થિર કરે છે, રાસાયણિક ખાતરોની જરૂરિયાત ઘટાડે છે.',
    rotation_reason: 'તમારા પાછલા પાકના આધારે, આ ફેરબદલી જમીનના સ્વાસ્થ્યને મહત્તમ કરશે.',
    rotation_advice_title: 'પાક ફેરબદલી સલાહકાર',
    crop_rotation: 'પાક ફેરબદલી સલાહકાર',
    select_previous_crop: 'પાછલો પાક પસંદ કરો',
    suggested_next: 'સુચિત આગામી પાક',
    all_crops: 'બધા પાક',
    top_recommendations: 'ટોચની જમીન ભલામણો',
    soil_match: 'જમીન મેચ',
    forecast_3day: '3-દિવસીય આગાહી',
    forecast_7day: '7-દિવસીય આગાહી',
    hourly_forecast: 'કલાકવાર આગાહી',
    weekly_forecast: 'સાપ્તાહિક આગાહી',
    weather_map: 'હવામાન નકશો',
    search_location: 'સ્થાન શોધો...',
    no_results: 'કોઈ પરિણામ મળ્યું નથી',
    use_current_location: 'વર્તમાન સ્થાનનો ઉપયોગ કરો',
    market: 'બજાર',
    market_prices: 'બજાર ભાવ',
    commodity: 'વસ્તુ',
    price_range: 'કિંમત શ્રેણી',
    modal_price: 'સરેરાશ કિંમત',
    select_state: 'રાજ્ય પસંદ કરો',
    all_states: 'બધા રાજ્યો',
    search_commodity: 'વસ્તુ શોધો...',
    latest_news: 'નવીનતમ કૃષિ સમાચાર',
    read_more: 'વધુ વાંચો',
    compare_crops: 'પાકની સરખામણી કરો',
    select_up_to_2: 'સરખામણી કરવા માટે વધુમાં વધુ ૨ પાક પસંદ કરો',
    yield_potential: 'ઉત્પાદન ક્ષમતા',
    soil_type: 'માટીનો પ્રકાર',
    ph_range: 'pH રેન્જ',
    temp_range: 'તાપમાન રેન્જ',
    water_needs: 'પાણીની જરૂરિયાત',
    sowing_time: 'વાવણીનો સમય',
    expert_tips: 'નિષ્ણાત ટિપ્સ',
    view_all: 'બધું જુઓ',
    price_alerts: 'કિંમત એલર્ટ',
    set_alert: 'એલર્ટ સેટ કરો',
    alert_threshold: 'એલર્ટ મર્યાદા',
    alert_condition: 'એલર્ટ સ્થિતિ',
    above: 'ઉપર',
    below: 'નીચે',
    alert_created: 'કિંમત એલર્ટ બનાવવામાં આવ્યું!',
    no_alerts: 'કોઈ સક્રિય કિંમત એલર્ટ નથી',
    notify_me: 'જ્યારે કિંમત હોય ત્યારે મને જાણ કરો',
  },
  kn: {
    language_name: 'ಕನ್ನಡ',
    welcome: 'ಕಿಸಾನ್ ಸೇನ್ಸ್‌ಗೆ ಸ್ವಾಗತ',
    soil_intelligence: 'ಮಣ್ಣಿನ ಬುದ್ಧಿಮತ್ತೆ',
    crop_advisor: 'ಬೆಳೆ ಸಲಹೆಗಾರ',
    weather_alerts: 'ಹವಾಮಾನ ಎಚ್ಚರಿಕೆಗಳು',
    voice_assistant: 'ವಾಯ್ಸ್ ಸಹಾಯಕ',
    check_soil: 'ನನ್ನ ಮಣ್ಣನ್ನು ಪರಿಶೀಲಿಸಿ',
    talk_to_ai: 'AI ಬಾಟ್‌ನೊಂದಿಗೆ ಕೆಲಸ ಮಾಡಿ',
    loading: 'ಡೇಟಾ ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
    location_needed: 'ಸ್ಥಾನೀಯ ಡೇಟಾಕ್ಕಾಗಿ ದಯವಿಟ್ಟು ಸ್ಥಳ ಪ್ರವೇಶವನ್ನು ಸಕ್ಷಮ ಮಾಡಿ।',
    error_loading: 'ಡೇಟಾ ಲೋಡ್ ಮಾಡುವಲ್ಲಿ ದೋಷ',
    retry: 'ಪುನಃ ಪ್ರಯತ್ನಿಸಿ',
    ph: 'pH',
    soc: 'ಜೈವ ಕಾರ್ಬನ್',
    dosage: 'ಖುರಾಕ್',
    application: 'ಅನ್ವಯ ವಿಧಾನ',
    treatment_steps: 'ಚಿಕಿತ್ಸೆ ಪಾಳಿಗಳು',
    disease_library: 'ರೋಗ ಗ್ರಂಥಾಲಯ',
    save: 'ಉಳಿಸಿಕೊಳ್ಳಿ',
    cancel: 'ರದ್ದುಮಾಡಿ',
    manual_input: 'ಹಸ್ತಚಾಲಿತ ಇನ್‌ಪುಟ್',
    select_language: 'ಭಾಷೆಯನ್ನು ಆಯ್ಕೆ ಮಾಡಿ',
    home: 'ಮುಖಪುಟ',
    soil: 'ಮಣ್ಣು',
    crops: 'ಬೆಳೆಗಳು',
    disease: 'ರೋಗ',
    weather: 'ಹವಾಮಾನ',
    sand: 'ಮರಳು',
    silt: 'ಹೂಳು',
    clay: 'ಜಿಗುಟು ಮಣ್ಣು',
    soil_texture: 'ಮಣ್ಣಿನ ವಿನ್ಯಾಸ',
    filter: 'ಫಿಲ್ಟರ್',
    severity: 'ತೀವ್ರತೆ',
    high: 'ಹೆಚ್ಚು',
    medium: 'ಮಧ್ಯಮ',
    low: 'ಕಡಿಮೆ',
    select_crops: 'ಬೆಳೆಗಳನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    select_severity: 'ತೀವ್ರತೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    clear_all: 'ಎಲ್ಲವನ್ನೂ ಅಳಿಸಿ',
    fungal_risk_title: 'ಶಿಲೀಂಧ್ರದ ಅಪಾಯ ಹೆಚ್ಚು',
    fungal_risk_desc: 'ಆರ್ದ್ರತೆಯು 80% ಕ್ಕಿಂತ ಹೆಚ್ಚಿದೆ. ಬೆಳೆಗಳಲ್ಲಿ ಶಿಲೀಂಧ್ರದ ಲಕ್ಷಣಗಳನ್ನು ಪರೀಕ್ಷಿಸಿ.',
    heat_stress_title: 'ಶಾಖದ ಒತ್ತಡದ ಎಚ್ಚರಿಕೆ',
    heat_stress_desc: 'ಅತಿಯಾದ ಶಾಖ ಪತ್ತೆಯಾಗಿದೆ ಅಥವಾ ನಿರೀಕ್ಷಿಸಲಾಗಿದೆ. ಸಾಕಷ್ಟು ನೀರಾವರಿಯನ್ನು ಖಚಿತಪಡಿಸಿಕೊಳ್ಳಿ.',
    frost_alert_title: 'ಮಂಜಿನ ಎಚ್ಚರಿಕೆ',
    frost_alert_desc: 'ಕಡಿಮೆ ತಾಪಮಾನ ನಿರೀಕ್ಷಿಸಲಾಗಿದೆ. ಸೂಕ್ಷ್ಮ ಬೆಳೆಗಳನ್ನು ಮಂಜಿನಿಂದ ರಕ್ಷಿಸಿ.',
    heavy_rain_title: 'ಭಾರೀ ಮಳೆಯ ಮುನ್ಸೂಚನೆ',
    heavy_rain_desc: 'ಮಳೆಯ ಹೆಚ್ಚಿನ ಸಂಭವನೀಯತೆ (>70%). ಅದರಂತೆ ಕೃಷಿ ಚಟುವಟಿಕೆಗಳನ್ನು ಯೋಜಿಸಿ.',
    sowing_window_title: 'ಬಿತ್ತನೆಗೆ ಸೂಕ್ತ ಸಮಯ',
    sowing_window_desc: 'ಪ್ರಸ್ತುತ ಪರಿಸ್ಥಿತಿಗಳು ಸಾಸಿವೆ ಬಿತ್ತನೆಗೆ ಸೂಕ್ತವಾಗಿವೆ.',
    rotation_importance_title: 'ಬೆಳೆ ಸರದಿ ಏಕೆ ಮುಖ್ಯ?',
    rotation_importance_desc: 'ಬೆಳೆ ಸರದಿಯು ಮಣ್ಣಿನ ಫಲವತ್ತತೆಯನ್ನು ಕಾಪಾಡಲು, ಕೀಟಗಳು ಮತ್ತು ರೋಗಗಳನ್ನು ಕಡಿಮೆ ಮಾಡಲು ಮತ್ತು ಮಣ್ಣಿನ ಆರೋಗ್ಯವನ್ನು ಸುಧಾರಿಸಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ.',
    learn_more: 'ವಿವರವಾದ ಮಾರ್ಗದರ್ಶಿ ನೋಡಿ',
    no_previous_data: 'ವೈಯಕ್ತಿಕಗೊಳಿಸಿದ ಬೆಳೆ ಸರದಿ ಸಲಹೆ ಪಡೆಯಲು ನಿಮ್ಮ ಹಿಂದಿನ ಬೆಳೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ.',
    cereal_benefit: 'ಗೋಧಿ ಮತ್ತು ಭತ್ತದಂತಹ ಧಾನ್ಯಗಳು ಹೆಚ್ಚಿನ ಇಳುವರಿ ಮತ್ತು ಸ್ಥಿರ ಆದಾಯವನ್ನು ನೀಡುತ್ತವೆ.',
    legume_benefit: 'ದ್ವಿದಳ ಧಾನ್ಯಗಳು ಮಣ್ಣಿನಲ್ಲಿ ಸಾರಜನಕವನ್ನು ಸ್ಥಿರಗೊಳಿಸುತ್ತವೆ, ರಾಸಾಯನಿಕ ಗೊಬ್ಬರಗಳ ಅಗತ್ಯವನ್ನು ಕಡಿಮೆ ಮಾಡುತ್ತದೆ.',
    rotation_reason: 'ನಿಮ್ಮ ಹಿಂದಿನ ಬೆಳೆಯ ಆಧಾರದ ಮೇಲೆ, ಈ ಸರದಿಯು ಮಣ್ಣಿನ ಆರೋಗ್ಯವನ್ನು ಹೆಚ್ಚಿಸುತ್ತದೆ.',
    rotation_advice_title: 'ಬೆಳೆ ಸರದಿ ಸಲಹೆಗಾರ',
    crop_rotation: 'ಬೆಳೆ ಸರದಿ ಸಲಹೆಗಾರ',
    select_previous_crop: 'ಹಿಂದಿನ ಬೆಳೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    suggested_next: 'ಸೂಚಿಸಲಾದ ಮುಂದಿನ ಬೆಳೆ',
    all_crops: 'ಎಲ್ಲಾ ಬೆಳೆಗಳು',
    top_recommendations: 'ಉನ್ನತ ಮಣ್ಣಿನ ಶಿಫಾರಸುಗಳು',
    soil_match: 'ಮಣ್ಣಿನ ಹೊಂದಾಣಿಕೆ',
    forecast_3day: '3-ದಿನದ ಮುನ್ಸೂಚನೆ',
    forecast_7day: '7-ದಿನದ ಮುನ್ಸೂಚನೆ',
    hourly_forecast: 'ಗಂಟೆಯ ಮುನ್ಸೂಚನೆ',
    weekly_forecast: 'ವಾರದ ಮುನ್ಸೂಚನೆ',
    weather_map: 'ಹವಾಮಾನ ನಕ್ಷೆ',
    search_location: 'ಸ್ಥಳವನ್ನು ಹುಡುಕಿ...',
    no_results: 'ಯಾವುದೇ ಫಲಿತಾಂಶಗಳು ಕಂಡುಬಂದಿಲ್ಲ',
    use_current_location: 'ಪ್ರಸ್ತುತ ಸ್ಥಳವನ್ನು ಬಳಸಿ',
    market: 'ಮಾರುಕಟ್ಟೆ',
    market_prices: 'ಮಾರುಕಟ್ಟೆ ಬೆಲೆಗಳು',
    commodity: 'ವಸ್ತು',
    price_range: 'ಬೆಲೆ ಶ್ರೇಣಿ',
    modal_price: 'ಸರಾಸರಿ ಬೆಲೆ',
    select_state: 'ರಾಜ್ಯವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    all_states: 'ಎಲ್ಲಾ ರಾಜ್ಯಗಳು',
    search_commodity: 'ವಸ್ತುವನ್ನು ಹುಡುಕಿ...',
    latest_news: 'ಇತ್ತೀಚಿನ ಕೃಷಿ ಸುದ್ದಿ',
    read_more: 'ಮತ್ತಷ್ಟು ಓದಿ',
    compare_crops: 'ಬೆಳೆಗಳ ಹೋಲಿಕೆ',
    select_up_to_2: 'ಹೋಲಿಸಲು ಗರಿಷ್ಠ 2 ಬೆಳೆಗಳನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    yield_potential: 'ಇಳುವರಿ ಸಾಮರ್ಥ್ಯ',
    soil_type: 'ಮಣ್ಣಿನ ವಿಧ',
    ph_range: 'pH ಶ್ರೇಣಿ',
    temp_range: 'ತಾಪಮಾನ ಶ್ರೇಣಿ',
    water_needs: 'ನೀರಿನ ಅವಶ್ಯಕತೆ',
    sowing_time: 'ಬಿತ್ತನೆ ಸಮಯ',
    expert_tips: 'ತಜ್ಞರ ಸಲಹೆಗಳು',
    view_all: 'ಎಲ್ಲವನ್ನೂ ನೋಡಿ',
    price_alerts: 'ಬೆಲೆ ಎಚ್ಚರಿಕೆಗಳು',
    set_alert: 'ಎಚ್ಚರಿಕೆ ಹೊಂದಿಸಿ',
    alert_threshold: 'ಎಚ್ಚರಿಕೆ ಮಿತಿ',
    alert_condition: 'ಎಚ್ಚರಿಕೆ ಸ್ಥಿತಿ',
    above: 'ಮೇಲೆ',
    below: 'ಕೆಳಗೆ',
    alert_created: 'ಬೆಲೆ ಎಚ್ಚರಿಕೆ ರಚಿಸಲಾಗಿದೆ!',
    no_alerts: 'ಯಾವುದೇ ಸಕ್ರಿಯ ಬೆಲೆ ಎಚ್ಚರಿಕೆಗಳಿಲ್ಲ',
    notify_me: 'ಬೆಲೆ ಹೀಗಿದ್ದಾಗ ನನಗೆ ತಿಳಿಸಿ',
  },
};
